// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createTerminal: (cols: number, rows: number) => typedError<string, string>(__TAURI_INVOKE("create_terminal", { cols, rows })),
	writeTerminal: (id: string, data: number[]) => typedError<null, string>(__TAURI_INVOKE("write_terminal", { id, data })),
	resizeTerminal: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_terminal", { id, cols, rows })),
	closeTerminal: (id: string) => typedError<null, string>(__TAURI_INVOKE("close_terminal", { id })),
	/**
	 *  返回会话当前 scrollback 快照（base64）。前端重连/remount 时用于重建屏幕，
	 *  对本地终端与远程 SSH 会话通用（按 backend session id 索引）。
	 */
	terminalSnapshot: (id: string) => typedError<string, string>(__TAURI_INVOKE("terminal_snapshot", { id })),
	dbListConnections: () => typedError<DbConnectionConfig[], string>(__TAURI_INVOKE("db_list_connections")),
	dbSaveConnection: (connection: DbConnectionConfig) => typedError<DbConnectionConfig, string>(__TAURI_INVOKE("db_save_connection", { connection })),
	dbDeleteConnection: (id: string) => typedError<null, string>(__TAURI_INVOKE("db_delete_connection", { id })),
	dbLoadSchemaFilters: () => typedError<SchemaFiltersSnapshot, string>(__TAURI_INVOKE("db_load_schema_filters")),
	dbSaveSchemaFilters: (snapshot: SchemaFiltersSnapshot) => typedError<null, string>(__TAURI_INVOKE("db_save_schema_filters", { snapshot })),
	dbTestConnection: (connection: DbConnectionConfig) => typedError<string, string>(__TAURI_INVOKE("db_test_connection", { connection })),
	dbListDatabases: (connection: DbConnectionConfig) => typedError<string[], string>(__TAURI_INVOKE("db_list_databases", { connection })),
	dbIntrospectSchema: (connection: DbConnectionConfig, schema: string | null) => typedError<DbIntrospectResult, string>(__TAURI_INVOKE("db_introspect_schema", { connection, schema })),
	dbIntrospectTable: (connection: DbConnectionConfig, schema: string | null, table: string) => typedError<DbTableSchema, string>(__TAURI_INVOKE("db_introspect_table", { connection, schema, table })),
	dbListTables: (connection: DbConnectionConfig, schema: string | null) => typedError<string[], string>(__TAURI_INVOKE("db_list_tables", { connection, schema })),
	/**  列出全部已保存连接。 */
	connList: () => typedError<Connection[], OmniError_Serialize>(__TAURI_INVOKE("conn_list")),
	/**  保存（新建或更新）连接。id 为空时后端生成。 */
	connSave: (connection: Connection) => typedError<Connection, OmniError_Serialize>(__TAURI_INVOKE("conn_save", { connection })),
	/**  删除连接。 */
	connDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("conn_delete", { id })),
	/**  测试连接连通性。当前支持 database（MySQL）；其余类型将在对应里程碑接入。 */
	connTest: (connection: Connection) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("conn_test", { connection })),
	/**
	 *  执行一个动作：按 kind 分发到执行引擎，过程通过 `action-progress` 事件流式回流，
	 *  完成后写入审计日志，返回退出码（0 成功）。
	 */
	executeAction: (action: ActionRequest) => typedError<number, OmniError_Serialize>(__TAURI_INVOKE("execute_action", { action })),
	/**
	 *  建立 SSH 连接并请求交互式 shell。返回会话 id；
	 *  shell 输出复用 `terminal-output` 事件，前端 xterm 无需区分本地/远程。
	 */
	sshConnect: (config: SshConfig, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect", { config, cols, rows })),
	/**  写入远端 shell。 */
	sshWrite: (id: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_write", { id, data })),
	/**  调整远端 PTY 窗口大小。 */
	sshResize: (id: string, cols: number, rows: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_resize", { id, cols, rows })),
	/**  断开并移除 SSH 会话。 */
	sshDisconnect: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_disconnect", { id })),
	/**  列出远端目录。 */
	sftpList: (id: string, path: string) => typedError<SftpEntry[], OmniError_Serialize>(__TAURI_INVOKE("sftp_list", { id, path })),
	/**  下载远端文件内容（字节）。 */
	sftpDownload: (id: string, path: string) => typedError<number[], OmniError_Serialize>(__TAURI_INVOKE("sftp_download", { id, path })),
	/**  上传内容到远端文件（覆盖）。 */
	sftpUpload: (id: string, path: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_upload", { id, path, data })),
	/**  在远程服务器创建目录。 */
	sftpMkdir: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_mkdir", { id, path })),
	/**  删除远程服务器上的文件。 */
	sftpRemove: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_remove", { id, path })),
	/**  读取 `~/.ssh/config` 中的 Host 条目（含 Include）。 */
	sshListConfigHosts: () => typedError<SshConfigEntry[], OmniError_Serialize>(__TAURI_INVOKE("ssh_list_config_hosts")),
	/**  按 `~/.ssh/config` 中的 Host 别名建立连接（使用 IdentityFile 等配置）。 */
	sshConnectConfigHost: (alias: string, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect_config_host", { alias, cols, rows })),
	/**  列出远程进程列表。 */
	sshProcessList: (id: string) => typedError<SshProcessInfo[], OmniError_Serialize>(__TAURI_INVOKE("ssh_process_list", { id })),
	checkUpdate: () => typedError<UpdateInfo, string>(__TAURI_INVOKE("check_update")),
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
};

/* Types */
/**  前端发起的动作请求。 */
export type ActionRequest = {
	id: string,
	/**  动作类型（terminal/docker/server/ssh/sql 等），决定分发到哪个 executor。 */
	kind: string,
	command?: string | null,
	resourceId?: string | null,
	envTag?: string | null,
	/**  工作目录（本地 shell 类执行可用）。 */
	cwd?: string | null,
};

/**
 *  统一连接模型。敏感凭据不在此，仅以 `credential_ref` 关联 [`crate::Vault`]。
 *  `config` 为 JSON 文本（不同 kind 字段不同，由前端按类型解析）。
 */
export type Connection = {
	id: string,
	kind: ConnectionKind,
	name: string,
	group?: string,
	envTag?: string,
	/**  连接配置 JSON 文本（host/port/user/database 等，因 kind 而异） */
	config?: string,
	credentialRef?: string | null,
	createdAt?: number | null,
	updatedAt?: number | null,
};

/**  连接类型。统一覆盖工作站内所有可持久化的连接资源。 */
export type ConnectionKind = "ssh" | "database" | "docker" | "panel" | "protocol";

export type DbColumnMeta = {
	name: string,
	type: string,
	isPk: boolean,
	isFk: boolean,
};

/**  数据库连接配置（与前端 `DbConnectionConfig` / Tauri IPC 一致）。 */
export type DbConnectionConfig = {
	id: string,
	name: string,
	db_type: string,
	host: string,
	port: number,
	user: string,
	password: string,
	database: string,
	/**  是否启用 SSL（MySQL 等）。 */
	ssl?: boolean,
	group?: string,
	status?: string,
};

export type DbIndexMeta = {
	name: string,
	columns: string[],
	unique: boolean,
};

export type DbIntrospectResult = {
	database: string,
	tables: DbTableSchema[],
};

export type DbTableSchema = {
	name: string,
	columns: DbColumnMeta[],
	indexes?: DbIndexMeta[],
};

/**  错误分类码。前端按 `code` 决定提示文案与重试策略。 */
export type ErrorCode = 
/**  未归类的内部错误 */
"internal" | 
/**  资源不存在（连接、会话、表等） */
"notFound" | 
/**  入参非法 */
"invalidInput" | 
/**  连接失败（网络、拒绝、不可达） */
"connection" | 
/**  认证失败（密码/密钥/Token 错误） */
"auth" | 
/**  权限不足 */
"permission" | 
/**  操作超时 */
"timeout" | 
/**  数据库错误 */
"database" | 
/**  SSH 相关错误 */
"ssh" | 
/**  终端/PTY 错误 */
"terminal" | 
/**  本地存储 / 凭据库错误 */
"storage" | 
/**  IO 错误 */
"io";

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError = OmniError_Serialize | OmniError_Deserialize;

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Deserialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause: string | null,
};

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Serialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause?: string | null,
};

/**  单个连接或库下的过滤项（与前端 `SchemaFilterState` 对应，可见项为列表）。 */
export type SchemaFilterRecord = {
	orderedNames: string[],
	visibleNames: string[],
};

/**  全部连接的 Schema 过滤快照。 */
export type SchemaFiltersSnapshot = {
	databaseFilters?: { [key in string]: SchemaFilterRecord },
	tableFilters?: { [key in string]: SchemaFilterRecord },
};

/**  SFTP 目录项。 */
export type SftpEntry = {
	name: string,
	isDir: boolean,
	size: number | null,
};

/**  SSH 认证方式。 */
export type SshAuth = { type: "password"; password: string } | { type: "privateKey"; pem: string; passphrase: string | null };

/**  SSH 连接配置。 */
export type SshConfig = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

/**  `~/.ssh/config` 中的一个 Host 条目（已展开 HostName）。 */
export type SshConfigEntry = {
	alias: string,
	hostName: string,
	user: string | null,
	port: number | null,
	identityFile: string | null,
};

/**  远程进程信息（ps aux 解析结果）。 */
export type SshProcessInfo = {
	user: string,
	pid: number,
	cpu: number | null,
	mem: number | null,
	vsz: number | null,
	rss: number | null,
	stat: string,
	start: string,
	time: string,
	command: string,
};

export type UpdateInfo = {
	available: boolean,
	version: string,
	body: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

