// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createTerminal: (cols: number, rows: number) => typedError<string, string>(__TAURI_INVOKE("create_terminal", { cols, rows })),
	writeTerminal: (id: string, data: number[]) => typedError<null, string>(__TAURI_INVOKE("write_terminal", { id, data })),
	resizeTerminal: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_terminal", { id, cols, rows })),
	closeTerminal: (id: string) => typedError<null, string>(__TAURI_INVOKE("close_terminal", { id })),
	/**
	 *  返回会话当前 scrollback 快照（base64）。前端重连/remount 时用于重建屏幕，
	 *  对本地终端与远程 SSH 会话通用（按 backend session id 索引）。
	 */
	terminalSnapshot: (id: string) => typedError<string, string>(__TAURI_INVOKE("terminal_snapshot", { id })),
	dbListConnections: () => typedError<DbConnectionConfig[], string>(__TAURI_INVOKE("db_list_connections")),
	dbSaveConnection: (connection: DbConnectionConfig) => typedError<DbConnectionConfig, string>(__TAURI_INVOKE("db_save_connection", { connection })),
	dbDeleteConnection: (id: string) => typedError<null, string>(__TAURI_INVOKE("db_delete_connection", { id })),
	dbLoadSchemaFilters: () => typedError<SchemaFiltersSnapshot, string>(__TAURI_INVOKE("db_load_schema_filters")),
	dbSaveSchemaFilters: (snapshot: SchemaFiltersSnapshot) => typedError<null, string>(__TAURI_INVOKE("db_save_schema_filters", { snapshot })),
	dbLoadSchemaTreeExpanded: () => typedError<SchemaTreeExpandedSnapshot, string>(__TAURI_INVOKE("db_load_schema_tree_expanded")),
	dbSaveSchemaTreeExpanded: (snapshot: SchemaTreeExpandedSnapshot) => typedError<null, string>(__TAURI_INVOKE("db_save_schema_tree_expanded", { snapshot })),
	dbLoadSchemaCache: () => typedError<SchemaCacheSnapshot_Serialize, string>(__TAURI_INVOKE("db_load_schema_cache")),
	dbSaveSchemaCache: (snapshot: SchemaCacheSnapshot_Deserialize) => typedError<null, string>(__TAURI_INVOKE("db_save_schema_cache", { snapshot })),
	dbTestConnection: (connection: DbConnectionConfig) => typedError<string, string>(__TAURI_INVOKE("db_test_connection", { connection })),
	dbListDatabases: (connection: DbConnectionConfig) => typedError<string[], string>(__TAURI_INVOKE("db_list_databases", { connection })),
	dbCreateDatabase: (args: CreateDatabaseArgs) => typedError<string, string>(__TAURI_INVOKE("db_create_database", { args })),
	dbIntrospectSchema: (connection: DbConnectionConfig, schema: string | null) => typedError<DbIntrospectResult_Serialize, string>(__TAURI_INVOKE("db_introspect_schema", { connection, schema })),
	dbListConnectionUsers: (connection: DbConnectionConfig) => typedError<DbUserMeta_Serialize[], string>(__TAURI_INVOKE("db_list_connection_users", { connection })),
	dbIntrospectTable: (connection: DbConnectionConfig, schema: string | null, table: string) => typedError<DbTableSchema_Serialize, string>(__TAURI_INVOKE("db_introspect_table", { connection, schema, table })),
	dbListTables: (connection: DbConnectionConfig, schema: string | null) => typedError<string[], string>(__TAURI_INVOKE("db_list_tables", { connection, schema })),
	dbTableDdl: (connection: DbConnectionConfig, schema: string | null, table: string) => typedError<string, string>(__TAURI_INVOKE("db_table_ddl", { connection, schema, table })),
	/**  列出全部已保存连接。 */
	connList: () => typedError<Connection[], OmniError_Serialize>(__TAURI_INVOKE("conn_list")),
	/**  保存（新建或更新）连接。id 为空时后端生成。 */
	connSave: (connection: Connection) => typedError<Connection, OmniError_Serialize>(__TAURI_INVOKE("conn_save", { connection })),
	/**  删除连接。 */
	connDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("conn_delete", { id })),
	/**  测试连接连通性。当前支持 database（MySQL）；其余类型将在对应里程碑接入。 */
	connTest: (connection: Connection) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("conn_test", { connection })),
	/**  汇总各模块在后端持有的会话与可复用连接，供状态栏连接池指示器展示。 */
	poolGetSummary: () => typedError<PoolSummary, OmniError_Serialize>(__TAURI_INVOKE("pool_get_summary")),
	/**
	 *  通用 1Panel API 请求（由 Rust 后端发起，避免 WebView CORS）。
	 *  `body` 为 JSON 字符串；返回 JSON 字符串。
	 */
	panel1panelRequest: (host: string, apiKey: string, method: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_request", { host, apiKey, method, path, body })),
	/**  1Panel 连通性测试。 */
	panel1panelTestConnection: (host: string, apiKey: string) => typedError<boolean, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_test_connection", { host, apiKey })),
	/**  获取 1Panel 应用图标（GET /apps/icon/:key），返回 data URL 或绝对 URL。 */
	panel1panelAppIcon: (host: string, apiKey: string, appKey: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_app_icon", { host, apiKey, appKey })),
	/**  1Panel 原始文本请求（用于日志下载等）。 */
	panel1panelRequestText: (host: string, apiKey: string, method: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_request_text", { host, apiKey, method, path, body })),
	/**
	 *  通用宝塔面板 API 请求（POST + 表单签名，由 Rust 后端发起并维护 Cookie）。
	 *  `path` 含 query，如 `/system?action=GetSystemTotal`；`body` 为额外字段的 JSON 对象字符串。
	 */
	panelBtRequest: (host: string, apiSk: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_bt_request", { host, apiSk, path, body })),
	/**  宝塔面板连通性测试。 */
	panelBtTestConnection: (host: string, apiSk: string) => typedError<boolean, OmniError_Serialize>(__TAURI_INVOKE("panel_bt_test_connection", { host, apiSk })),
	/**
	 *  ???? Docker ??????? Engine + ???? docker ?????
	 *  ?????????????????????????? `docker_probe_connection` ?????
	 */
	dockerListConnections: () => typedError<DockerConnectionInfo[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_connections")),
	/**  ??????????? */
	dockerProbeConnection: (connectionId: string) => typedError<DockerProbe, OmniError_Serialize>(__TAURI_INVOKE("docker_probe_connection", { connectionId })),
	dockerResetSshSession: (connectionId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_reset_ssh_session", { connectionId })),
	/**  ?? Docker Engine ????????????? */
	dockerGetLocalEngineStatus: () => typedError<DockerLocalEngineStatus, OmniError_Serialize>(__TAURI_INVOKE("docker_get_local_engine_status")),
	/**  ?????? Docker Desktop??????????? */
	dockerStartLocalEngine: () => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_start_local_engine")),
	/**  ??????? */
	dockerGetOverview: (connectionId: string) => typedError<DockerOverview, OmniError_Serialize>(__TAURI_INVOKE("docker_get_overview", { connectionId })),
	/**  `docker system df` ??????? */
	dockerGetSystemDiskUsage: (connectionId: string) => typedError<DockerSystemDiskUsage, OmniError_Serialize>(__TAURI_INVOKE("docker_get_system_disk_usage", { connectionId })),
	/**  ?????`filter` ? all/running/stopped? */
	dockerListContainers: (connectionId: string, filter: string | null) => typedError<DockerContainerSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_containers", { connectionId, filter })),
	/**  ????? */
	dockerInspectContainer: (connectionId: string, containerId: string) => typedError<DockerContainerDetail, OmniError_Serialize>(__TAURI_INVOKE("docker_inspect_container", { connectionId, containerId })),
	/**
	 *  ?????????start/stop/restart/kill/pause/unpause/remove?
	 *  ??????kill/remove????????????????
	 */
	dockerContainerAction: (connectionId: string, containerId: string, action: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_container_action", { connectionId, containerId, action })),
	/**  ??????????tail ???????? `docker_stream_container_logs`? */
	dockerContainerLogs: (connectionId: string, containerId: string, tail: number) => typedError<DockerLogLine[], OmniError_Serialize>(__TAURI_INVOKE("docker_container_logs", { connectionId, containerId, tail })),
	/**
	 *  ????????????? streamId?????? `docker-log` ?????
	 *  ??/???? `docker-log-end` ??????? Engine ???? follow?
	 *  SSH Engine ?????? tail?follow ??????
	 */
	dockerStreamContainerLogs: (connectionId: string, containerId: string, tail: number, follow: boolean) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_stream_container_logs", { connectionId, containerId, tail, follow })),
	/**  ???????? */
	dockerStopLogStream: (streamId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_stop_log_stream", { streamId })),
	/**  ????? */
	dockerListImages: (connectionId: string) => typedError<DockerImageSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_images", { connectionId })),
	/**  ???????????????? */
	dockerRemoveImage: (connectionId: string, imageId: string, force: boolean) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_remove_image", { connectionId, imageId, force })),
	/**  ?????????????????? */
	dockerPruneImages: (connectionId: string) => typedError<DockerPruneResult, OmniError_Serialize>(__TAURI_INVOKE("docker_prune_images", { connectionId })),
	/**  ?????????????????? */
	dockerPruneBuildCache: (connectionId: string) => typedError<DockerPruneResult, OmniError_Serialize>(__TAURI_INVOKE("docker_prune_build_cache", { connectionId })),
	/**  ?????`docker inspect`?? */
	dockerInspectImage: (connectionId: string, imageId: string) => typedError<DockerImageDetail, OmniError_Serialize>(__TAURI_INVOKE("docker_inspect_image", { connectionId, imageId })),
	/**  ??????`docker history`?? */
	dockerImageHistory: (connectionId: string, imageId: string) => typedError<DockerImageHistoryLayer[], OmniError_Serialize>(__TAURI_INVOKE("docker_image_history", { connectionId, imageId })),
	/**
	 *  Create container interactive terminal session. Returns sessionId;
	 *  output is emitted via `terminal-output` events for xterm binding.
	 */
	dockerCreateExecSession: (connectionId: string, containerId: string, shell: string | null, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_create_exec_session", { connectionId, containerId, shell, cols, rows })),
	/**  ?????? stdin? */
	dockerExecWrite: (sessionId: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_write", { sessionId, data })),
	/**  ????????? */
	dockerExecResize: (sessionId: string, cols: number, rows: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_resize", { sessionId, cols, rows })),
	/**  ??????????? stdin ??????? */
	dockerExecClose: (sessionId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_close", { sessionId })),
	/**  ?? Compose ???????????? */
	dockerListComposeProjects: (connectionId: string) => typedError<DockerComposeProject[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_compose_projects", { connectionId })),
	/**  Compose ?????up/down/restart/pull/logs?? */
	dockerComposeAction: (connectionId: string, action: DockerComposeAction, request: DockerComposeRequest) => typedError<DockerComposeResult, OmniError_Serialize>(__TAURI_INVOKE("docker_compose_action", { connectionId, action, request })),
	dockerListNetworks: (connectionId: string) => typedError<DockerNetworkSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_networks", { connectionId })),
	dockerCreateNetwork: (connectionId: string, request: DockerCreateNetworkRequest) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_create_network", { connectionId, request })),
	dockerRemoveNetwork: (connectionId: string, name: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_remove_network", { connectionId, name })),
	/**  ?????`docker network inspect`?? */
	dockerInspectNetwork: (connectionId: string, name: string) => typedError<DockerNetworkDetail, OmniError_Serialize>(__TAURI_INVOKE("docker_inspect_network", { connectionId, name })),
	dockerConnectNetwork: (connectionId: string, network: string, containerId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_connect_network", { connectionId, network, containerId })),
	dockerDisconnectNetwork: (connectionId: string, network: string, containerId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_disconnect_network", { connectionId, network, containerId })),
	dockerListVolumes: (connectionId: string) => typedError<DockerVolumeSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_volumes", { connectionId })),
	dockerCreateVolume: (connectionId: string, request: DockerCreateVolumeRequest) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_create_volume", { connectionId, request })),
	dockerRemoveVolume: (connectionId: string, name: string, force: boolean) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_remove_volume", { connectionId, name, force })),
	/**  ????`docker volume inspect`?? */
	dockerInspectVolume: (connectionId: string, name: string) => typedError<DockerVolumeDetail, OmniError_Serialize>(__TAURI_INVOKE("docker_inspect_volume", { connectionId, name })),
	dockerPruneVolumes: (connectionId: string) => typedError<DockerPruneVolumesResult, OmniError_Serialize>(__TAURI_INVOKE("docker_prune_volumes", { connectionId })),
	dockerListContainerDir: (connectionId: string, containerId: string, path: string) => typedError<DockerFileEntry[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_container_dir", { connectionId, containerId, path })),
	dockerReadContainerFile: (connectionId: string, containerId: string, path: string, maxBytes: number) => typedError<number[], OmniError_Serialize>(__TAURI_INVOKE("docker_read_container_file", { connectionId, containerId, path, maxBytes })),
	dockerWriteContainerFile: (connectionId: string, containerId: string, path: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_write_container_file", { connectionId, containerId, path, data })),
	/**  ????????? `docker_image_progress` ????? `progress_channel` ??? */
	dockerPullImage: (connectionId: string, image: string, progressChannel: string) => typedError<DockerPullResult, OmniError_Serialize>(__TAURI_INVOKE("docker_pull_image", { connectionId, image, progressChannel })),
	/**  ????????? `docker_image_progress` ????? `progress_channel` ??? */
	dockerPushImage: (connectionId: string, image: string, progressChannel: string) => typedError<DockerPullResult, OmniError_Serialize>(__TAURI_INVOKE("docker_push_image", { connectionId, image, progressChannel })),
	/**  ????????? tag? */
	dockerTagImage: (connectionId: string, source: string, target: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_tag_image", { connectionId, source, target })),
	/**  ?????Dockerfile?????? `progress_channel` ????? */
	dockerBuildImage: (connectionId: string, context: DockerBuildContext, progressChannel: string) => typedError<DockerBuildResult, OmniError_Serialize>(__TAURI_INVOKE("docker_build_image", { connectionId, context, progressChannel })),
	/**
	 *  ???? stats ?????? streamId??????? `docker-stats` ?????
	 *  ??/???? `docker-stats-end` ?????
	 */
	dockerStreamStats: (connectionId: string, containerId: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_stream_stats", { connectionId, containerId })),
	/**  ???? stats ?? */
	dockerStopStatsStream: (streamId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_stop_stats_stream", { streamId })),
	/**
	 *  Probe a remote SSH host for Docker daemon availability.
	 *  Returns Docker version info if found, or an error if Docker is not installed/running.
	 */
	dockerProbeSshDocker: (sshConnectionId: string) => typedError<DockerAutoDetectResult, OmniError_Serialize>(__TAURI_INVOKE("docker_probe_ssh_docker", { sshConnectionId })),
	/**
	 *  List SSH connections available for Docker binding.
	 *  Returns connections that are in "connected" state in the SSH pool.
	 */
	dockerListSshHosts: () => typedError<SshHostInfo[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_ssh_hosts")),
	/**  ??????? SSH ???? Docker ??????????? Docker ??? */
	dockerScanSshDockerHosts: (autoSave: boolean) => typedError<DockerScanResult, OmniError_Serialize>(__TAURI_INVOKE("docker_scan_ssh_docker_hosts", { autoSave })),
	/**  ?????????? ID? */
	dockerCreateContainer: (connectionId: string, request: DockerCreateContainerRequest) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_create_container", { connectionId, request })),
	dockerSwarmInit: (connectionId: string, listenAddr: string | null, advertiseAddr: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_swarm_init", { connectionId, listenAddr, advertiseAddr })),
	dockerSwarmJoin: (connectionId: string, remoteAddrs: string[], token: string, listenAddr: string | null) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_swarm_join", { connectionId, remoteAddrs, token, listenAddr })),
	dockerSwarmLeave: (connectionId: string, force: boolean) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_swarm_leave", { connectionId, force })),
	dockerSwarmInspect: (connectionId: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_swarm_inspect", { connectionId })),
	dockerServiceList: (connectionId: string) => typedError<DockerServiceSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_service_list", { connectionId })),
	dockerServiceCreate: (connectionId: string, request: DockerCreateServiceRequest) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_service_create", { connectionId, request })),
	dockerServiceUpdate: (connectionId: string, serviceId: string, replicas: number | null, image: string | null) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_service_update", { connectionId, serviceId, replicas, image })),
	dockerServiceRemove: (connectionId: string, serviceId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_service_remove", { connectionId, serviceId })),
	dockerServiceLogs: (connectionId: string, serviceId: string, tail: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_service_logs", { connectionId, serviceId, tail })),
	dockerNodeList: (connectionId: string) => typedError<DockerNodeSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_node_list", { connectionId })),
	dockerNodeInspect: (connectionId: string, nodeId: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_node_inspect", { connectionId, nodeId })),
	dockerNodeUpdate: (connectionId: string, nodeId: string, availability: string | null, labels: DockerKeyValue[] | null) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_node_update", { connectionId, nodeId, availability, labels })),
	dockerNodeRemove: (connectionId: string, nodeId: string, force: boolean) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_node_remove", { connectionId, nodeId, force })),
	dockerStackDeploy: (connectionId: string, name: string, composeContent: string, env: string[] | null) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_stack_deploy", { connectionId, name, composeContent, env })),
	dockerStackList: (connectionId: string) => typedError<DockerStackSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_stack_list", { connectionId })),
	dockerStackRemove: (connectionId: string, name: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_stack_remove", { connectionId, name })),
	dockerStackServices: (connectionId: string, name: string) => typedError<DockerServiceSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_stack_services", { connectionId, name })),
	/**
	 *  执行一个动作：按 kind 分发到执行引擎，过程通过 `action-progress` 事件流式回流，
	 *  完成后写入审计日志，返回退出码（0 成功）。
	 */
	executeAction: (action: ActionRequest) => typedError<number, OmniError_Serialize>(__TAURI_INVOKE("execute_action", { action })),
	/**
	 *  建立 SSH 连接并请求交互式 shell。返回会话 id；
	 *  shell 输出复用 `terminal-output` 事件，前端 xterm 无需区分本地/远程。
	 */
	sshConnect: (config: SshConfig_Deserialize, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect", { config, cols, rows })),
	/**  写入远端 shell。 */
	sshWrite: (id: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_write", { id, data })),
	/**  调整远端 PTY 窗口大小。 */
	sshResize: (id: string, cols: number, rows: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_resize", { id, cols, rows })),
	/**  断开并移除 SSH 会话。 */
	sshDisconnect: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_disconnect", { id })),
	/**  列出远端目录。 */
	sftpList: (id: string, path: string) => typedError<SftpEntry[], OmniError_Serialize>(__TAURI_INVOKE("sftp_list", { id, path })),
	/**  下载远端文件内容（字节）。 */
	sftpDownload: (id: string, path: string) => typedError<number[], OmniError_Serialize>(__TAURI_INVOKE("sftp_download", { id, path })),
	/**  上传内容到远端文件（覆盖）。 */
	sftpUpload: (id: string, path: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_upload", { id, path, data })),
	/**  在远程服务器创建目录。 */
	sftpMkdir: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_mkdir", { id, path })),
	/**  删除远程服务器上的文件。 */
	sftpRemove: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_remove", { id, path })),
	/**  重命名远程文件/目录。 */
	sftpRename: (id: string, oldPath: string, newPath: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_rename", { id, oldPath, newPath })),
	/**  修改远程文件权限（通过 exec chmod）。 */
	sftpChmod: (id: string, path: string, mode: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_chmod", { id, path, mode })),
	/**  读取 `~/.ssh/config` 中的 Host 条目（含 Include）。 */
	sshListConfigHosts: () => typedError<SshConfigEntry[], OmniError_Serialize>(__TAURI_INVOKE("ssh_list_config_hosts")),
	/**  将 `~/.ssh/config` 中的 Host 同步到本地持久化连接存储（按 Host 名称匹配更新）。 */
	sshSyncConfigHosts: () => typedError<SshConfigSyncResult, OmniError_Serialize>(__TAURI_INVOKE("ssh_sync_config_hosts")),
	/**  按 `~/.ssh/config` 中的 Host 别名建立连接（使用 IdentityFile 等配置）。 */
	sshConnectConfigHost: (alias: string, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect_config_host", { alias, cols, rows })),
	/**  列出远程进程列表。 */
	sshProcessList: (id: string) => typedError<SshProcessInfo_Serialize[], OmniError_Serialize>(__TAURI_INVOKE("ssh_process_list", { id })),
	/**  概览页：连接池建立 SSH 会话并拉取系统指标与进程列表。 */
	sshPoolLoadOverview: (resourceId: string) => typedError<SshHostOverview_Serialize, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_load_overview", { resourceId })),
	/**  释放连接池中指定资源的 SSH 会话（离开概览等场景）。 */
	sshPoolRelease: (resourceId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_release", { resourceId })),
	/**  监控页：复用连接池会话，仅拉取系统指标。 */
	sshPoolFetchStats: (resourceId: string) => typedError<HostSystemStats, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_fetch_stats", { resourceId })),
	/**  获取所有 SSH 主机的连接状态快照。 */
	sshPoolGetStatuses: () => typedError<PoolStatusEvent[], OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_get_statuses")),
	/**  获取当前已建立 SSH 会话的主机 ID 列表。 */
	sshPoolGetActiveSessions: () => typedError<string[], OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_get_active_sessions")),
	/**  开启持续监控采集（后端后台轮询并推送 stats）。 */
	sshPoolSubscribeMonitoring: (resourceId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_subscribe_monitoring", { resourceId })),
	/**  关闭持续监控采集。 */
	sshPoolUnsubscribeMonitoring: (resourceId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_unsubscribe_monitoring", { resourceId })),
	/**  独立刷新进程列表（概览页局部刷新）。 */
	sshPoolLoadProcesses: (resourceId: string) => typedError<SshProcessInfo_Serialize[], OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_load_processes", { resourceId })),
	/**  按 PID 深入查询远程进程详情（启动命令、cwd、exe、root、打开文件）。 */
	sshPoolProcessDetail: (resourceId: string, pid: number) => typedError<SshProcessDetail_Serialize, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_process_detail", { resourceId, pid })),
	/**  强制终止远程进程（默认 SIGKILL）。 */
	sshPoolKillProcess: (resourceId: string, pid: number, signal: number | null) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_kill_process", { resourceId, pid, signal })),
	/**  拉取本机 CPU / 内存 / 磁盘指标。 */
	localFetchStats: () => typedError<HostSystemStats, OmniError_Serialize>(__TAURI_INVOKE("local_fetch_stats")),
	/**  列出本机进程。 */
	localListProcesses: () => typedError<SshProcessInfo_Serialize[], OmniError_Serialize>(__TAURI_INVOKE("local_list_processes")),
	/**  查询本机进程详情。 */
	localProcessDetail: (pid: number) => typedError<SshProcessDetail_Serialize, OmniError_Serialize>(__TAURI_INVOKE("local_process_detail", { pid })),
	/**  强制终止本机进程。 */
	localKillProcess: (pid: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("local_kill_process", { pid })),
	/**
	 *  创建 SSH 隧道（端口转发）。
	 *  通过 SSH exec 运行 `ssh -L/-R/-D` 命令实现，隧道进程在后台运行。
	 */
	sshCreateTunnel: (connectionId: string, tunnelType: string, localPort: number, remoteHost: string, remotePort: number) => typedError<SshTunnelInfo, OmniError_Serialize>(__TAURI_INVOKE("ssh_create_tunnel", { connectionId, tunnelType, localPort, remoteHost, remotePort })),
	/**  关闭 SSH 隧道。 */
	sshCloseTunnel: (tunnelId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_close_tunnel", { tunnelId })),
	/**  列出活跃隧道。 */
	sshListTunnels: () => typedError<SshTunnelInfo[], OmniError_Serialize>(__TAURI_INVOKE("ssh_list_tunnels")),
	/**  列出本地 ~/.ssh/ 下的密钥。 */
	sshListKeys: () => typedError<SshKeyInfo[], OmniError_Serialize>(__TAURI_INVOKE("ssh_list_keys")),
	/**  生成 SSH 密钥对。 */
	sshGenerateKey: (keyType: string, bits: number | null, comment: string, passphrase: string) => typedError<SshKeyInfo, OmniError_Serialize>(__TAURI_INVOKE("ssh_generate_key", { keyType, bits, comment, passphrase })),
	/**  导入 SSH 私钥（写入 ~/.ssh/ 目录）。 */
	sshImportKey: (name: string, privateKey: string) => typedError<SshKeyInfo, OmniError_Serialize>(__TAURI_INVOKE("ssh_import_key", { name, privateKey })),
	/**  删除 SSH 密钥。 */
	sshDeleteKey: (name: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_delete_key", { name })),
	/**  读取密钥对应的公钥文件内容（`~/.ssh/{name}.pub`）。 */
	sshReadKeyPublic: (name: string) => typedError<string | null, OmniError_Serialize>(__TAURI_INVOKE("ssh_read_key_public", { name })),
	/**
	 *  将文本写入用户通过 `plugin-dialog::save` 选择的任意路径。
	 * 
	 *  Tauri 2 的 `plugin-fs` 默认只允许在 capability scope 内的目录写入；本命令直接调用 std::fs
	 *  绕开范围限制，调用方必须已通过 save dialog 拿到用户明确授权的路径。
	 */
	writeTextFile: (path: string, contents: string) => typedError<string, string>(__TAURI_INVOKE("write_text_file", { path, contents })),
	/**  列出文件管理器可用连接（含内置本机）。 */
	fileListConnections: () => typedError<FileManagerConnectionInfo[], OmniError_Serialize>(__TAURI_INVOKE("file_list_connections")),
	/**  保存文件连接（凭据写入 Vault）。 */
	fileSaveConnection: (connection: Connection, secret: string | null) => typedError<Connection, OmniError_Serialize>(__TAURI_INVOKE("file_save_connection", { connection, secret })),
	/**  测试文件连接。 */
	fileTestConnection: (connectionId: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("file_test_connection", { connectionId })),
	/**  列出目录内容。 */
	fileListDir: (connectionId: string, path: string) => typedError<FileEntry[], OmniError_Serialize>(__TAURI_INVOKE("file_list_dir", { connectionId, path })),
	/**  读取文件内容（字节）。 */
	fileReadFile: (connectionId: string, path: string, maxBytes: number | null) => typedError<number[], OmniError_Serialize>(__TAURI_INVOKE("file_read_file", { connectionId, path, maxBytes })),
	/**  上传文件（覆盖）。 */
	fileUploadFile: (connectionId: string, path: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("file_upload_file", { connectionId, path, data })),
	/**  下载文件到本地路径。 */
	fileDownloadFile: (connectionId: string, remotePath: string, localPath: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("file_download_file", { connectionId, remotePath, localPath })),
	/**  创建目录。 */
	fileMkdir: (connectionId: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("file_mkdir", { connectionId, path })),
	/**  重命名文件/目录。 */
	fileRename: (connectionId: string, oldPath: string, newPath: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("file_rename", { connectionId, oldPath, newPath })),
	/**  删除文件/目录。 */
	fileDelete: (connectionId: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("file_delete", { connectionId, path })),
	/**  本机常用目录快捷路径。 */
	fileLocalQuickPaths: () => typedError<FileQuickPaths, OmniError_Serialize>(__TAURI_INVOKE("file_local_quick_paths")),
	checkUpdate: () => typedError<UpdateInfo, string>(__TAURI_INVOKE("check_update")),
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	/**  列出知识条目（可选按 kind / tag 过滤）。 */
	knowledgeList: (kind: string | null, tag: string | null) => typedError<KnowledgeEntry[], OmniError_Serialize>(__TAURI_INVOKE("knowledge_list", { kind, tag })),
	/**  按 id 获取单条知识。 */
	knowledgeGet: (id: string) => typedError<{
	id: string,
	/**  "snippet" | "case" | "ai" */
	kind: string,
	title: string,
	/**  Markdown 正文 */
	content: string,
	tags: string[],
	/**  "safe" | "readonly" | "medium" | "dangerous" */
	riskLevel: string,
	source: string,
	/**  "dev" | "staging" | "production" */
	envTag: string,
	/**  代码语言（snippet 时有意义） */
	language: string,
	usageCount: number | null,
	createdAt?: number | null,
	updatedAt?: number | null,
	/**  父节点 id，空字符串表示根级 */
	parentId?: string,
	/**  "folder" | "document" */
	nodeType?: string,
	sortOrder?: number | null,
} | null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_get", { id })),
	/**  保存（新建或更新）知识条目。 */
	knowledgeSave: (entry: KnowledgeEntry) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_save", { entry })),
	/**  删除知识条目。 */
	knowledgeDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_delete", { id })),
	/**  FTS5 全文搜索（可选按 kind 过滤）。 */
	knowledgeSearch: (query: string, kind: string | null) => typedError<KnowledgeSearchResult[], OmniError_Serialize>(__TAURI_INVOKE("knowledge_search", { query, kind })),
	/**  列出所有不重复的 tag。 */
	knowledgeTags: () => typedError<string[], OmniError_Serialize>(__TAURI_INVOKE("knowledge_tags")),
	/**  递增使用次数。 */
	knowledgeIncrementUsage: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_increment_usage", { id })),
	/**  列出全部待办列表。 */
	knowledgeTodoList: () => typedError<KnowledgeTodoList[], OmniError_Serialize>(__TAURI_INVOKE("knowledge_todo_list")),
	/**  保存（新建或更新）待办列表。 */
	knowledgeTodoSave: (list: KnowledgeTodoList) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_todo_save", { list })),
	/**  删除待办列表。 */
	knowledgeTodoDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("knowledge_todo_delete", { id })),
	/**  从 PDF 文件导入知识文档（提取文本并保存为 document 条目）。 */
	knowledgeImportPdf: (path: string, parentId: string | null) => typedError<KnowledgeEntry, OmniError_Serialize>(__TAURI_INVOKE("knowledge_import_pdf", { path, parentId })),
	/**  列出所有工作流。 */
	workflowList: () => typedError<Workflow[], OmniError_Serialize>(__TAURI_INVOKE("workflow_list")),
	/**  按 id 获取工作流详情（含步骤）。 */
	workflowGet: (id: string) => typedError<WorkflowDetail, OmniError_Serialize>(__TAURI_INVOKE("workflow_get", { id })),
	/**  创建或更新工作流。 */
	workflowSave: (req: SaveWorkflowRequest) => typedError<WorkflowDetail, OmniError_Serialize>(__TAURI_INVOKE("workflow_save", { req })),
	/**  删除工作流（级联删除步骤和执行记录）。 */
	workflowDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("workflow_delete", { id })),
	/**  获取工作流执行历史。 */
	workflowExecutions: (workflowId: string, limit: number) => typedError<WorkflowExecution[], OmniError_Serialize>(__TAURI_INVOKE("workflow_executions", { workflowId, limit })),
	/**
	 *  Start executing a workflow. Returns the execution ID immediately.
	 *  Steps execute sequentially in a background task.
	 */
	workflowRun: (id: string) => typedError<WorkflowExecution, OmniError_Serialize>(__TAURI_INVOKE("workflow_run", { id })),
	/**  Cancel a running workflow execution. */
	workflowStop: (executionId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("workflow_stop", { executionId })),
	/**  Get execution detail with step results. */
	workflowGetExecution: (executionId: string) => typedError<WorkflowExecutionDetail, OmniError_Serialize>(__TAURI_INVOKE("workflow_get_execution", { executionId })),
	/**  列出任务，可选按状态过滤。 */
	taskList: (statusFilter: string | null, limit: number) => typedError<Task[], OmniError_Serialize>(__TAURI_INVOKE("task_list", { statusFilter, limit })),
	/**  获取单个任务。 */
	taskGet: (id: string) => typedError<Task, OmniError_Serialize>(__TAURI_INVOKE("task_get", { id })),
	/**  创建或更新任务。 */
	taskSave: (req: SaveTaskRequest) => typedError<Task, OmniError_Serialize>(__TAURI_INVOKE("task_save", { req })),
	/**  更新任务状态。 */
	taskUpdateStatus: (id: string, status: TaskStatus) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("task_update_status", { id, status })),
	/**  删除任务。 */
	taskDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("task_delete", { id })),
	/**
	 *  执行一个任务：从存储加载 → 分发到执行引擎 → 流式回流输出 → 更新状态。
	 * 
	 *  任务在后台异步执行，函数立即返回。执行过程中通过以下事件通知前端：
	 *  - `task-output`   — 流式 stdout/stderr 输出（payload: `{ taskId, stream, chunk }`）
	 *  - `task-status`   — 状态变更（payload: `{ taskId, status }`）
	 */
	taskRun: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("task_run", { id })),
	/**  停止一个正在运行的任务。异步任务将被中止，任务状态标记为 cancelled。 */
	taskStop: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("task_stop", { id })),
	/**  获取任务执行输出。 */
	taskGetOutput: (id: string) => typedError<Task, OmniError_Serialize>(__TAURI_INVOKE("task_get_output", { id })),
	grpcConnect: (config: GrpcConnectionConfig) => typedError<string, string>(__TAURI_INVOKE("grpc_connect", { config })),
	grpcCall: (connectionId: string, request: GrpcCallRequest) => typedError<GrpcCallResponse, string>(__TAURI_INVOKE("grpc_call", { connectionId, request })),
	grpcListConnections: () => typedError<string[], string>(__TAURI_INVOKE("grpc_list_connections")),
	grpcClose: (connectionId: string) => typedError<null, string>(__TAURI_INVOKE("grpc_close", { connectionId })),
	httpSaveRequest: (req: SavedHttpRequest) => typedError<null, string>(__TAURI_INVOKE("http_save_request", { req })),
	httpListRequests: (collectionId: string | null) => typedError<SavedHttpRequest[], string>(__TAURI_INVOKE("http_list_requests", { collectionId })),
	httpDeleteRequest: (id: string) => typedError<null, string>(__TAURI_INVOKE("http_delete_request", { id })),
	httpAddHistory: (entry: HttpHistoryEntry) => typedError<null, string>(__TAURI_INVOKE("http_add_history", { entry })),
	httpListHistory: (limit: number | null) => typedError<HttpHistoryEntry[], string>(__TAURI_INVOKE("http_list_history", { limit })),
	httpClearHistory: () => typedError<null, string>(__TAURI_INVOKE("http_clear_history")),
	httpSaveCollection: (col: HttpCollection) => typedError<null, string>(__TAURI_INVOKE("http_save_collection", { col })),
	httpListCollections: () => typedError<HttpCollection[], string>(__TAURI_INVOKE("http_list_collections")),
	httpDeleteCollection: (id: string) => typedError<null, string>(__TAURI_INVOKE("http_delete_collection", { id })),
	snifferListInterfaces: () => typedError<NetworkInterface[], string>(__TAURI_INVOKE("sniffer_list_interfaces")),
	snifferStartCapture: (iface: string, filter: string) => typedError<string, string>(__TAURI_INVOKE("sniffer_start_capture", { iface, filter })),
	snifferStopCapture: (captureId: string) => typedError<null, string>(__TAURI_INVOKE("sniffer_stop_capture", { captureId })),
	snifferGetPackets: (captureId: string, limit: number | null) => typedError<SnifferPacket[], string>(__TAURI_INVOKE("sniffer_get_packets", { captureId, limit })),
	snifferGetStats: (captureId: string) => typedError<CaptureStats, string>(__TAURI_INVOKE("sniffer_get_stats", { captureId })),
	modbusConnect: (config: ModbusConfig) => typedError<string, string>(__TAURI_INVOKE("modbus_connect", { config })),
	modbusReadCoils: (id: string, addr: number, qty: number) => typedError<boolean[], string>(__TAURI_INVOKE("modbus_read_coils", { id, addr, qty })),
	modbusReadDiscreteInputs: (id: string, addr: number, qty: number) => typedError<boolean[], string>(__TAURI_INVOKE("modbus_read_discrete_inputs", { id, addr, qty })),
	modbusReadHoldingRegisters: (id: string, addr: number, qty: number) => typedError<number[], string>(__TAURI_INVOKE("modbus_read_holding_registers", { id, addr, qty })),
	modbusReadInputRegisters: (id: string, addr: number, qty: number) => typedError<number[], string>(__TAURI_INVOKE("modbus_read_input_registers", { id, addr, qty })),
	modbusWriteSingleCoil: (id: string, addr: number, value: boolean) => typedError<null, string>(__TAURI_INVOKE("modbus_write_single_coil", { id, addr, value })),
	modbusWriteSingleRegister: (id: string, addr: number, value: number) => typedError<null, string>(__TAURI_INVOKE("modbus_write_single_register", { id, addr, value })),
	modbusWriteMultipleCoils: (id: string, addr: number, values: boolean[]) => typedError<null, string>(__TAURI_INVOKE("modbus_write_multiple_coils", { id, addr, values })),
	modbusWriteMultipleRegisters: (id: string, addr: number, values: number[]) => typedError<null, string>(__TAURI_INVOKE("modbus_write_multiple_registers", { id, addr, values })),
	modbusDisconnect: (id: string) => typedError<null, string>(__TAURI_INVOKE("modbus_disconnect", { id })),
	/**  Set the proxy configuration from frontend settings. */
	setProxyConfig: (config: ProxyConfig) => typedError<null, string>(__TAURI_INVOKE("set_proxy_config", { config })),
	/**  Get the current proxy configuration (for backend use). */
	getProxyConfig: () => typedError<ProxyConfig, string>(__TAURI_INVOKE("get_proxy_config")),
	/**  读取 AI 模型配置 JSON 文件。文件不存在时返回默认空配置。 */
	aiModelsLoad: () => typedError<AiModelsFile, string>(__TAURI_INVOKE("ai_models_load")),
	/**  原子写入 AI 模型配置 JSON 文件:先写临时文件再 rename,防止崩溃时半写。 */
	aiModelsSave: (file: AiModelsFile) => typedError<null, string>(__TAURI_INVOKE("ai_models_save", { file })),
	dbSqlFilesLoad: () => typedError<DbSqlFilesFile, string>(__TAURI_INVOKE("db_sql_files_load")),
	dbSqlFilesSave: (file: DbSqlFilesFile) => typedError<null, string>(__TAURI_INVOKE("db_sql_files_save", { file })),
	mcpListServices: () => typedError<McpServiceView[], string>(__TAURI_INVOKE("mcp_list_services")),
	mcpUpsertService: (input: UpsertMcpServiceInput) => typedError<McpServiceView, string>(__TAURI_INVOKE("mcp_upsert_service", { input })),
	mcpDeleteService: (id: string) => typedError<null, string>(__TAURI_INVOKE("mcp_delete_service", { id })),
	mcpSetServiceEnabled: (id: string, enabled: boolean) => typedError<McpServiceView, string>(__TAURI_INVOKE("mcp_set_service_enabled", { id, enabled })),
	mcpSetServiceRunning: (id: string, running: boolean) => typedError<McpServiceView, string>(__TAURI_INVOKE("mcp_set_service_running", { id, running })),
	mcpListServiceTools: (id: string) => typedError<McpToolInfo[], string>(__TAURI_INVOKE("mcp_list_service_tools", { id })),
	mcpCallTool: (serviceId: string, toolName: string, toolArguments: string) => typedError<McpToolCallResult, string>(__TAURI_INVOKE("mcp_call_tool", { serviceId, toolName, toolArguments })),
};

/* Types */
/**  前端发起的动作请求。 */
export type ActionRequest = {
	id: string,
	/**  动作类型（terminal/docker/server/ssh/sql 等），决定分发到哪个 executor。 */
	kind: string,
	command?: string | null,
	resourceId?: string | null,
	envTag?: string | null,
	/**  工作目录（本地 shell 类执行可用）。 */
	cwd?: string | null,
};

/**
 *  AI 提供商配置。前端 camelCase 字段名（providerName / baseUrl / ...），
 *  通过 `#[serde(rename_all = "camelCase")]` 与之对齐。
 */
export type AiModelProvider = {
	id: string,
	providerName: string,
	apiStandard: string,
	baseUrl: string,
	apiKey: string,
	modelNames: string[],
	disabledModelNames?: string[],
	createdAt: number | null,
};

/**  持久化文件结构。版本号用于前端迁移。 */
export type AiModelsFile = {
	version?: number,
	providers?: AiModelProvider[],
};

/**  抓包统计信息。 */
export type CaptureStats = {
	captureId: string,
	iface: string,
	filter: string,
	running: boolean,
	packetCount: number | null,
	startedAt: string,
};

/**
 *  统一连接模型。敏感凭据不在此，仅以 `credential_ref` 关联 [`crate::Vault`]。
 *  `config` 为 JSON 文本（不同 kind 字段不同，由前端按类型解析）。
 */
export type Connection = {
	id: string,
	kind: ConnectionKind,
	name: string,
	group?: string,
	envTag?: string,
	/**  全局资源标签，如 `os:Ubuntu 24.04.2 LTS`（key:value 字符串列表） */
	tags?: string[],
	/**  连接配置 JSON 文本（host/port/user/database 等，因 kind 而异） */
	config?: string,
	credentialRef?: string | null,
	createdAt?: number | null,
	updatedAt?: number | null,
};

/**  连接类型。统一覆盖工作站内所有可持久化的连接资源。 */
export type ConnectionKind = "ssh" | "database" | "docker" | "panel" | "protocol" | "file";

/**  创建数据库参数。name 必填；charset 可选，留空时使用服务器默认。 */
export type CreateDatabaseArgs = {
	connection: DbConnectionConfig,
	name: string,
	charset?: string | null,
	collation?: string | null,
};

export type DbColumnMeta = {
	name: string,
	type: string,
	isPk: boolean,
	isFk: boolean,
};

/**  数据库连接配置（与前端 `DbConnectionConfig` / Tauri IPC 一致）。 */
export type DbConnectionConfig = {
	id: string,
	name: string,
	db_type: string,
	host: string,
	port: number,
	user: string,
	password: string,
	database: string,
	/**  是否启用 SSL（MySQL 等）。 */
	ssl?: boolean,
	group?: string,
	status?: string,
	/**  是否启用；`false` 表示连接已关闭（禁用），不参与查询与库表加载。 */
	enabled?: boolean,
};

export type DbIndexMeta = {
	name: string,
	columns: string[],
	unique: boolean,
};

export type DbIntrospectResult = DbIntrospectResult_Serialize | DbIntrospectResult_Deserialize;

export type DbIntrospectResult_Deserialize = {
	database: string,
	tables: DbTableSchema_Deserialize[],
	views?: DbTableSchema_Deserialize[],
	routines?: DbRoutineMeta[],
};

export type DbIntrospectResult_Serialize = {
	database: string,
	tables: DbTableSchema_Serialize[],
	views: DbTableSchema_Serialize[],
	routines: DbRoutineMeta[],
};

export type DbRoutineMeta = {
	name: string,
	routineType: string,
};

export type DbSqlFileNode = {
	id: string,
	type: string,
	name: string,
	parentId: string | null,
	sql?: string | null,
	connId?: string | null,
	database?: string | null,
	updatedAt: number | null,
};

export type DbSqlFilesFile = {
	version?: number,
	nodes?: DbSqlFileNode[],
};

export type DbTableSchema = DbTableSchema_Serialize | DbTableSchema_Deserialize;

export type DbTableSchema_Deserialize = {
	name: string,
	columns: DbColumnMeta[],
	indexes?: DbIndexMeta[],
	comment?: string | null,
};

export type DbTableSchema_Serialize = {
	name: string,
	columns: DbColumnMeta[],
	indexes: DbIndexMeta[],
	comment?: string | null,
};

export type DbUserMeta = DbUserMeta_Serialize | DbUserMeta_Deserialize;

export type DbUserMeta_Deserialize = {
	name: string,
	host?: string | null,
};

export type DbUserMeta_Serialize = {
	name: string,
	host?: string | null,
};

export type DiskStats = {
	total: number | null,
	used: number | null,
	available: number | null,
};

/**  Docker auto-detection result. */
export type DockerAutoDetectResult = {
	available: boolean,
	version: string | null,
	os: string | null,
	containers: number,
	images: number,
	error: string | null,
};

/**  镜像构建的输入上下文。 */
export type DockerBuildContext = {
	contextDir: string,
	tag: string,
	dockerfile: string | null,
	buildArgs: string[],
	useBuildKit: boolean,
};

/**  镜像构建结果。 */
export type DockerBuildResult = {
	tag: string,
	imageId: string | null,
};

/**  连接级能力探测结果。前端据此决定页签/按钮显隐与降级。 */
export type DockerCapabilities = {
	canOverview: boolean,
	canStreamLogs: boolean,
	canContainerExec: boolean,
	canInspect: boolean,
	canManageContainers: boolean,
	canManageImages: boolean,
	canCompose: boolean,
	canPrune: boolean,
	readOnly: boolean,
	source: DockerConnectionSource,
};

/**  Compose 生命周期动作。 */
export type DockerComposeAction = "up" | "down" | "restart" | "pull" | "logs";

/**  Compose 项目（按 `com.docker.compose.project` 标签聚合容器得到）。 */
export type DockerComposeProject = {
	name: string,
	workingDir: string | null,
	configFiles: string | null,
	serviceCount: number,
	containerCount: number,
	runningContainerCount: number,
	services: DockerComposeService[],
};

/**  单条 Compose 命令的入参。 */
export type DockerComposeRequest = {
	project: string,
	workingDir: string | null,
	configFile: string | null,
	services: string[],
	detached: boolean,
};

/**  单条 Compose 命令的结果。 */
export type DockerComposeResult = {
	action: DockerComposeAction,
	project: string,
	stdoutExcerpt: string,
	stderrExcerpt: string,
	exitCode: number,
};

/**  Compose 服务（按 `com.docker.compose.service` 标签聚合）。 */
export type DockerComposeService = {
	name: string,
	image: string,
	containerCount: number,
	runningContainerCount: number,
};

/**  连接信息（列表与工作区头部展示）。 */
export type DockerConnectionInfo = {
	connectionId: string,
	name: string,
	source: DockerConnectionSource,
	status: DockerConnectionStatus,
	hostLabel: string,
	environment: string,
	engineVersion: string | null,
	apiVersion: string | null,
	containersRunning: number,
	containersTotal: number,
	warningMessage: string | null,
	/**  与 SSH / Server 模块贯通上下文用：绑定的 SSH 连接 id。 */
	boundSshConnectionId: string | null,
};

/**  Docker 连接来源。前端只消费统一资源模型，来源差异由后端 adapter 屏蔽。 */
export type DockerConnectionSource = 
/**  本地 Docker Engine / Docker Desktop。 */
"local-engine" | 
/**  远程 Docker Engine API（TCP/TLS）。 */
"remote-engine" | 
/**  通过 SSH 宿主机调用远程 `docker` CLI。 */
"ssh-engine" | 
/**  通过 1Panel 面板 API 适配。 */
"one-panel" | 
/**  预留：宝塔 / Portainer 等其他面板 API。 */
"panel-adapter";

/**  连接状态。 */
export type DockerConnectionStatus = "online" | "degraded" | "offline";

/**  容器详情。 */
export type DockerContainerDetail = {
	summary: DockerContainerSummary,
	command: string | null,
	restartPolicy: string | null,
	exitCode: number | null,
	env: DockerKeyValue[],
	mounts: DockerMount[],
	networks: DockerNetworkAttachment[],
};

/**  容器列表项。 */
export type DockerContainerSummary = {
	id: string,
	shortId: string,
	name: string,
	image: string,
	/**  归一化生命周期：running / exited / paused / restarting / created / dead / unknown。 */
	state: string,
	/**  Docker 原始状态文本，例如 "Up 2 hours"。 */
	statusText: string,
	running: boolean,
	ports: DockerPort[],
	networks: string[],
	createdAt: number | null,
};

/**  创建容器请求。 */
export type DockerCreateContainerRequest = {
	/**  镜像名称（含 tag）。 */
	image: string,
	/**  容器名称，留空则 Docker 自动生成。 */
	name: string | null,
	/**  端口映射：host_port:container_port/tcp|udp。 */
	ports: string[],
	/**  卷挂载：host_path:container_path[:ro]。 */
	volumes: string[],
	/**  环境变量：KEY=VALUE。 */
	env: string[],
	/**  连接的网络名。 */
	network: string | null,
	/**  启动命令覆盖。 */
	cmd: string[] | null,
	/**  重启策略：no|always|on-failure|unless-stopped。 */
	restartPolicy: string | null,
	/**  自动删除容器（退出后自动 rm）。 */
	autoRemove: boolean,
};

/**  创建网络请求。 */
export type DockerCreateNetworkRequest = {
	name: string,
	driver: string | null,
	internal: boolean,
	subnet: string | null,
};

/**  创建服务请求。 */
export type DockerCreateServiceRequest = {
	name: string,
	image: string,
	replicas: number | null,
	ports: string[],
	env: string[],
	networks: string[],
	command: string | null,
	constraints: string[],
};

/**  创建卷请求。 */
export type DockerCreateVolumeRequest = {
	name: string,
	driver: string | null,
	labels: ([string, string])[],
};

/**  `docker system df` 单项磁盘占用。 */
export type DockerDiskUsageItem = {
	sizeBytes: number | null,
	reclaimableBytes: number | null,
	totalCount: number | null,
	activeCount: number | null,
};

/**  容器内文件条目。 */
export type DockerFileEntry = {
	name: string,
	path: string,
	sizeBytes: number | null,
	modifiedAt: number | null,
	mode: number,
	isDir: boolean,
	isSymlink: boolean,
};

/**  `docker inspect .Config` 关键字段。 */
export type DockerImageConfig = {
	env: string[],
	cmd: string | null,
	entrypoint: string | null,
	workingDir: string | null,
	user: string | null,
	exposedPorts: string[],
	labels: DockerKeyValue[],
	volumes: string[],
};

/**  镜像详情。 */
export type DockerImageDetail = {
	/**  与 `DockerImageSummary.id` 相同。 */
	id: string,
	/**  所有 repo:tag 引用。 */
	repoTags: string[],
	architecture: string | null,
	os: string | null,
	driver: string | null,
	createdAt: number | null,
	sizeBytes: number | null,
	author: string | null,
	comment: string | null,
	config: DockerImageConfig,
	/**  历史层（`docker history` 精简版）。 */
	history: DockerImageHistoryLayer[],
};

/**  `docker history` 单层。 */
export type DockerImageHistoryLayer = {
	id: string,
	createdAt: number | null,
	createdBy: string,
	sizeBytes: number | null,
	comment: string,
	tags: string[],
};

/**  镜像列表项。 */
export type DockerImageSummary = {
	id: string,
	shortId: string,
	repository: string,
	tag: string,
	sizeBytes: number | null,
	createdAt: number | null,
	containers: number | null,
	dangling: boolean,
};

/**  键值对（环境变量、标签）。 */
export type DockerKeyValue = {
	key: string,
	value: string,
};

/**  本地 Docker Engine / Desktop 安装与运行状态。 */
export type DockerLocalEngineStatus = {
	/**  是否检测到 Docker Desktop / Engine 已安装。 */
	installed: boolean,
	/**  是否已通过 socket/pipe 连通。 */
	running: boolean,
	/**  是否支持应用内一键启动（通常为 Docker Desktop）。 */
	canStart: boolean,
	/**  安装类型：`docker-desktop` / `docker-engine` / `none`。 */
	installKind: string,
};

/**  日志行。 */
export type DockerLogLine = {
	/**  stdout / stderr。 */
	stream: string,
	message: string,
};

/**  挂载信息。 */
export type DockerMount = {
	kind: string,
	source: string,
	destination: string,
	readOnly: boolean,
};

/**  网络挂载。 */
export type DockerNetworkAttachment = {
	name: string,
	ipAddress: string | null,
};

/**  已挂接网络容器摘要。 */
export type DockerNetworkContainer = {
	containerId: string,
	name: string,
	endpointId: string | null,
	macAddress: string | null,
	ipv4Address: string | null,
	ipv6Address: string | null,
};

/**  网络详情。 */
export type DockerNetworkDetail = {
	/**  与 `DockerNetworkSummary.id` 相同。 */
	id: string,
	name: string,
	driver: string,
	scope: string,
	internal: boolean,
	enableIpv6: boolean,
	createdAt: number | null,
	/**  子网 + 网关 列表（来自 IPAM）。 */
	subnets: DockerNetworkSubnet[],
	/**  当前已连接容器。 */
	containers: DockerNetworkContainer[],
	labels: DockerKeyValue[],
	/**  网络选项（如 `com.docker.network.bridge.name=br0`）。 */
	options: DockerKeyValue[],
};

/**  IPAM 子网条目。 */
export type DockerNetworkSubnet = {
	subnet: string | null,
	gateway: string | null,
	ipRange: string | null,
};

/**  网络摘要。 */
export type DockerNetworkSummary = {
	id: string,
	name: string,
	driver: string,
	scope: string,
	internal: boolean,
	createdAt: number | null,
};

/**  Docker 节点信息。 */
export type DockerNodeSummary = {
	id: string,
	hostname: string,
	status: string,
	availability: string,
	role: string,
	engineVersion: string,
	addr: string,
	labels: DockerKeyValue[],
};

/**  总览页数据。 */
export type DockerOverview = {
	capabilities: DockerCapabilities,
	summary: DockerResourceSummary,
	engineVersion: string | null,
	warningMessage: string | null,
};

/**  端口映射。 */
export type DockerPort = {
	privatePort: number,
	publicPort: number | null,
	protocol: string,
	ip: string | null,
};

/**  探测结果。 */
export type DockerProbe = {
	status: DockerConnectionStatus,
	engineVersion: string | null,
	apiVersion: string | null,
	capabilities: DockerCapabilities,
	warningMessage: string | null,
};

/**  镜像清理结果。 */
export type DockerPruneResult = {
	deleted: string[],
	freedSpaceBytes: number | null,
};

/**  卷清理结果。 */
export type DockerPruneVolumesResult = {
	deleted: string[],
	freedSpaceBytes: number | null,
};

/**  镜像拉取结果。 */
export type DockerPullResult = {
	image: string,
	tag: string,
	digest: string | null,
};

/**  资源统计（总览页）。 */
export type DockerResourceSummary = {
	containersTotal: number,
	containersRunning: number,
	containersStopped: number,
	images: number,
};

/**  ?? SSH ?? Docker ????? */
export type DockerScanItemResult = {
	sshConnectionId: string,
	sshName: string,
	available: boolean,
	probe: DockerAutoDetectResult | null,
	dockerConnectionId: string | null,
	/**  created | updated | unchanged | no_docker | failed */
	action: string,
	error: string | null,
};

/**  ??????? SSH ?? Docker ????? */
export type DockerScanResult = {
	scanned: number,
	created: number,
	updated: number,
	unchanged: number,
	noDocker: number,
	failed: number,
	items: DockerScanItemResult[],
};

/**  Docker 服务摘要。 */
export type DockerServiceSummary = {
	id: string,
	name: string,
	image: string,
	mode: string,
	replicas: number | null,
	runningReplicas: number | null,
	ports: string[],
	createdAt: string,
	updatedAt: string,
};

/**  Docker Stack 信息。 */
export type DockerStackSummary = {
	name: string,
	services: number,
	orchestrator: string,
	namespace: string,
};

/**  `docker system df` 汇总。 */
export type DockerSystemDiskUsage = {
	images: DockerDiskUsageItem,
	containers: DockerDiskUsageItem,
	volumes: DockerDiskUsageItem,
	buildCache: DockerDiskUsageItem,
};

/**  卷详情。 */
export type DockerVolumeDetail = {
	/**  与 `DockerVolumeSummary.name` 相同。 */
	name: string,
	driver: string,
	mountpoint: string,
	scope: string,
	createdAt: number | null,
	sizeBytes: number | null,
	labels: DockerKeyValue[],
	/**  驱动选项。 */
	options: DockerKeyValue[],
	/**  引用计数字段（来自 `Volume.UsageData.RefCount`）。 */
	referenceCount: number | null,
};

/**  卷摘要。 */
export type DockerVolumeSummary = {
	name: string,
	driver: string,
	mountpoint: string,
	createdAt: number | null,
	sizeBytes: number | null,
	inUse: boolean,
};

/**  错误分类码。前端按 `code` 决定提示文案与重试策略。 */
export type ErrorCode = 
/**  未归类的内部错误 */
"internal" | 
/**  资源不存在（连接、会话、表等） */
"notFound" | 
/**  入参非法 */
"invalidInput" | 
/**  连接失败（网络、拒绝、不可达） */
"connection" | 
/**  认证失败（密码/密钥/Token 错误） */
"auth" | 
/**  权限不足 */
"permission" | 
/**  操作超时 */
"timeout" | 
/**  数据库错误 */
"database" | 
/**  SSH 相关错误 */
"ssh" | 
/**  终端/PTY 错误 */
"terminal" | 
/**  本地存储 / 凭据库错误 */
"storage" | 
/**  IO 错误 */
"io";

export type ExecutionStatus = "running" | "completed" | "failed" | "cancelled";

/**  文件条目（统一模型）。 */
export type FileEntry = {
	name: string,
	path: string,
	/**  `file` | `dir` */
	kind: string,
	size: number | null,
	modified: number | null,
	permissions: string | null,
};

/**  文件管理器连接摘要。 */
export type FileManagerConnectionInfo = {
	id: string,
	name: string,
	/**  local | ftp | sftp | s3 */
	protocol: string,
	status: string,
	group: string,
};

/**  本机常用目录快捷路径。 */
export type FileQuickPaths = {
	home: string,
	desktop: string,
	documents: string,
	downloads: string,
};

/**  gRPC 调用请求。 */
export type GrpcCallRequest = {
	/**  完整方法名，如 `mypackage.MyService/MyMethod` */
	method: string,
	/**  请求 JSON（将序列化为 protobuf） */
	requestJson: string,
	/**  自定义 metadata */
	metadata?: ([string, string])[],
};

/**  gRPC 调用响应。 */
export type GrpcCallResponse = {
	/**  响应 JSON */
	responseJson: string,
	/**  HTTP 状态码 */
	statusCode: number,
	/**  gRPC 状态 */
	grpcStatus: number,
	/**  响应 metadata */
	headers: ([string, string])[],
	/**  耗时(ms) */
	durationMs: number | null,
};

/**  gRPC 连接配置。 */
export type GrpcConnectionConfig = {
	/**  服务器地址，如 `http://localhost:50051` */
	endpoint: string,
	/**  自定义 metadata（header） */
	metadata?: ([string, string])[],
	/**  是否使用 TLS */
	useTls?: boolean,
};

export type HostSystemStats = {
	hostId: string,
	hostName: string,
	load: string,
	cpuCores: number,
	cpuUsage: number | null,
	memory: MemoryStats,
	disk: DiskStats,
	network: NetworkStats,
	osInfo: string,
	timestamp: number | null,
};

/**  HTTP 集合。 */
export type HttpCollection = {
	id: string,
	name: string,
	description: string,
	createdAt: number | null,
	updatedAt: number | null,
};

/**  HTTP 请求历史记录。 */
export type HttpHistoryEntry = {
	id: string,
	method: string,
	url: string,
	statusCode: number | null,
	responseTimeMs: number | null,
	requestSize: number | null,
	responseSize: number | null,
	createdAt: number | null,
};

/**  知识条目模型。 */
export type KnowledgeEntry = {
	id: string,
	/**  "snippet" | "case" | "ai" */
	kind: string,
	title: string,
	/**  Markdown 正文 */
	content: string,
	tags: string[],
	/**  "safe" | "readonly" | "medium" | "dangerous" */
	riskLevel: string,
	source: string,
	/**  "dev" | "staging" | "production" */
	envTag: string,
	/**  代码语言（snippet 时有意义） */
	language: string,
	usageCount: number | null,
	createdAt?: number | null,
	updatedAt?: number | null,
	/**  父节点 id，空字符串表示根级 */
	parentId?: string,
	/**  "folder" | "document" */
	nodeType?: string,
	sortOrder?: number | null,
};

/**  FTS5 搜索结果：原文 + snippet 摘要。 */
export type KnowledgeSearchResult = {
	entry: KnowledgeEntry,
	snippet: string,
	/**  关键词相关性评分（0-100），分数越高越相关。 */
	score: number | null,
};

/**  待办列表中的单项。 */
export type KnowledgeTodoItem = {
	id: string,
	text: string,
	done: boolean,
};

/**  知识库待办列表。 */
export type KnowledgeTodoList = {
	id: string,
	title: string,
	items: KnowledgeTodoItem[],
	sortOrder?: number | null,
	createdAt?: number | null,
	updatedAt?: number | null,
};

export type McpEnvEntry = {
	key: string,
	value: string,
};

export type McpServiceRuntimeStatus = "running" | "stopped" | "starting" | "error";

export type McpServiceView = {
	id: string,
	name: string,
	enabled: boolean,
	builtin: boolean,
	transport: McpTransport,
	createdAt: number | null,
	status: McpServiceRuntimeStatus,
	endpoint?: string | null,
	errorMessage?: string | null,
};

export type McpSseTransport = {
	url: string,
};

export type McpStdioTransport = {
	command: string,
	args?: string[],
	env?: { [key in string]: string },
	cwd?: string | null,
};

export type McpToolCallResult = {
	content: string,
	isError: boolean,
};

export type McpToolInfo = {
	name: string,
	description?: string | null,
};

export type McpTransport = { kind: "stdio"; config: McpStdioTransport } | { kind: "sse"; config: McpSseTransport };

export type McpTransportKind = "stdio" | "sse";

export type MemoryStats = {
	total: number | null,
	used: number | null,
	available: number | null,
};

/**  Modbus 连接配置。 */
export type ModbusConfig = {
	host: string,
	port: number,
	slave_id: number,
	mode: string,
};

/**  网络接口信息。 */
export type NetworkInterface = {
	name: string,
	description: string,
	addresses: string[],
};

export type NetworkStats = {
	rxBytes: number | null,
	txBytes: number | null,
};

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError = OmniError_Serialize | OmniError_Deserialize;

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Deserialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause: string | null,
};

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Serialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause?: string | null,
};

/**  单类连接的活跃 / 空闲统计。 */
export type PoolCategorySummary = {
	kind: string,
	active: number,
	idle: number,
};

/**  发射到前端的单个主机连接状态 */
export type PoolStatusEvent = {
	resourceId: string,
	status: string,
	error: string | null,
};

/**  全局连接池汇总。 */
export type PoolSummary = {
	active: number,
	idle: number,
	categories: PoolCategorySummary[],
};

/**  Proxy 配置，从前端设置同步到后端。 */
export type ProxyConfig = {
	enabled: boolean,
	protocol: string,
	host: string,
	port: number,
	username: string,
	password: string,
};

export type RiskLevel = "low" | "medium" | "high" | "critical" | "read_only";

export type SaveStepRequest = {
	id: string | null,
	name: string,
	description: string,
	step_type: StepType,
	command: string,
	step_order: number,
};

export type SaveTaskRequest = {
	id: string | null,
	task_type: TaskType,
	title: string,
	description: string,
	resource_id: string,
	resource_name: string,
	env_tag: string,
	command: string,
	risk: TaskRisk,
	status: TaskStatus,
	source: TaskSource,
};

export type SaveWorkflowRequest = {
	id: string | null,
	name: string,
	description: string,
	workflow_type: WorkflowType,
	risk_level: RiskLevel,
	target: string,
	env_tag: string,
	steps: SaveStepRequest[],
};

/**  保存的 HTTP 请求。 */
export type SavedHttpRequest = {
	id: string,
	name: string,
	method: string,
	url: string,
	headers: string,
	body: string,
	authType: string,
	authValue: string,
	collectionId: string | null,
	createdAt: number | null,
	updatedAt: number | null,
};

export type SchemaCacheColumn = {
	name: string,
	type: string,
	isPk: boolean,
	isFk: boolean,
};

export type SchemaCacheConnection = SchemaCacheConnection_Serialize | SchemaCacheConnection_Deserialize;

export type SchemaCacheConnection_Deserialize = {
	databases?: SchemaCacheDatabase_Deserialize[],
	users?: SchemaCacheUser_Deserialize[],
	refreshedAt?: number | null,
	error?: string | null,
};

export type SchemaCacheConnection_Serialize = {
	databases: SchemaCacheDatabase_Serialize[],
	users: SchemaCacheUser_Serialize[],
	refreshedAt?: number | null,
	error?: string | null,
};

export type SchemaCacheDatabase = SchemaCacheDatabase_Serialize | SchemaCacheDatabase_Deserialize;

export type SchemaCacheDatabase_Deserialize = {
	name: string,
	tables?: SchemaCacheTable_Deserialize[],
	views?: SchemaCacheTable_Deserialize[],
	routines?: SchemaCacheRoutine[],
	loadError?: string | null,
};

export type SchemaCacheDatabase_Serialize = {
	name: string,
	tables: SchemaCacheTable_Serialize[],
	views: SchemaCacheTable_Serialize[],
	routines: SchemaCacheRoutine[],
	loadError?: string | null,
};

export type SchemaCacheIndex = {
	name: string,
	columns: string[],
	unique: boolean,
};

export type SchemaCacheRoutine = {
	name: string,
	routineType: string,
};

/**  全部连接的 Schema 缓存快照。 */
export type SchemaCacheSnapshot = SchemaCacheSnapshot_Serialize | SchemaCacheSnapshot_Deserialize;

/**  全部连接的 Schema 缓存快照。 */
export type SchemaCacheSnapshot_Deserialize = {
	connections?: { [key in string]: SchemaCacheConnection_Deserialize },
};

/**  全部连接的 Schema 缓存快照。 */
export type SchemaCacheSnapshot_Serialize = {
	connections: { [key in string]: SchemaCacheConnection_Serialize },
};

export type SchemaCacheTable = SchemaCacheTable_Serialize | SchemaCacheTable_Deserialize;

export type SchemaCacheTable_Deserialize = {
	name: string,
	columns?: SchemaCacheColumn[],
	indexes?: SchemaCacheIndex[],
	comment?: string | null,
};

export type SchemaCacheTable_Serialize = {
	name: string,
	columns: SchemaCacheColumn[],
	indexes: SchemaCacheIndex[],
	comment?: string | null,
};

export type SchemaCacheUser = SchemaCacheUser_Serialize | SchemaCacheUser_Deserialize;

export type SchemaCacheUser_Deserialize = {
	name: string,
	host?: string | null,
};

export type SchemaCacheUser_Serialize = {
	name: string,
	host?: string | null,
};

/**  单个连接或库下的过滤项（与前端 `SchemaFilterState` 对应，可见项为列表）。 */
export type SchemaFilterRecord = {
	orderedNames: string[],
	visibleNames: string[],
};

/**  全部连接的 Schema 过滤快照。 */
export type SchemaFiltersSnapshot = {
	databaseFilters?: { [key in string]: SchemaFilterRecord },
	tableFilters?: { [key in string]: SchemaFilterRecord },
};

/**  Schema 树已展开节点 id 快照（与前端 `expanded` Set 的 key 一致）。 */
export type SchemaTreeExpandedSnapshot = {
	expandedNodeIds?: string[],
};

/**  SFTP 目录项。 */
export type SftpEntry = {
	name: string,
	isDir: boolean,
	size: number | null,
};

/**  捕获的数据包。 */
export type SnifferPacket = {
	id: number | null,
	timestamp: string,
	srcIp: string,
	dstIp: string,
	protocol: string,
	srcPort: number | null,
	dstPort: number | null,
	length: number | null,
	payloadHex: string,
};

/**  SSH 认证方式。 */
export type SshAuth = SshAuth_Serialize | SshAuth_Deserialize;

/**  SSH 认证方式。 */
export type SshAuth_Deserialize = ({ password: {
	type: "password",
	password: string,
} }) & { privateKey?: never } | ({ privateKey: {
	type: "privateKey",
} & {
	pem?: string | null,
	passphrase: string | null,
} & {
	keyPath?: string | null,
} }) & { password?: never };

/**  SSH 认证方式。 */
export type SshAuth_Serialize = ({ type: "password"; password: string }) & { keyPath?: never; passphrase?: never; pem?: never } | ({ type: "privateKey"; pem: string | null; keyPath: string | null; passphrase: string | null }) & { password?: never };

/**  SSH 连接配置。 */
export type SshConfig = SshConfig_Serialize | SshConfig_Deserialize;

/**  `~/.ssh/config` 中的一个 Host 条目（已展开 HostName）。 */
export type SshConfigEntry = {
	alias: string,
	hostName: string,
	user: string | null,
	port: number | null,
	identityFile: string | null,
};

export type SshConfigSyncFailure = {
	alias: string,
	reason: string,
};

export type SshConfigSyncResult = {
	added: number,
	updated: number,
	skipped: number,
	failures: SshConfigSyncFailure[],
};

/**  SSH 连接配置。 */
export type SshConfig_Deserialize = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth_Deserialize,
};

/**  SSH 连接配置。 */
export type SshConfig_Serialize = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth_Serialize,
};

/**  SSH host info for Docker connection binding. */
export type SshHostInfo = {
	connectionId: string,
	name: string,
	host: string,
	port: number,
	user: string,
};

/**  概览页一次加载的完整数据（系统指标 + 进程列表）。 */
export type SshHostOverview = SshHostOverview_Serialize | SshHostOverview_Deserialize;

/**  概览页一次加载的完整数据（系统指标 + 进程列表）。 */
export type SshHostOverview_Deserialize = {
	stats: HostSystemStats,
	processes: SshProcessInfo_Deserialize[],
};

/**  概览页一次加载的完整数据（系统指标 + 进程列表）。 */
export type SshHostOverview_Serialize = {
	stats: HostSystemStats,
	processes: SshProcessInfo_Serialize[],
};

/**  SSH 密钥信息。 */
export type SshKeyInfo = {
	name: string,
	keyType: string,
	path: string,
	fingerprint: string,
	comment: string,
};

/**  通过 `/proc/<pid>` 深入采集的进程详情。 */
export type SshProcessDetail = SshProcessDetail_Serialize | SshProcessDetail_Deserialize;

/**  通过 `/proc/<pid>` 深入采集的进程详情。 */
export type SshProcessDetail_Deserialize = {
	pid: number,
	commandLine?: string | null,
	args?: string[],
	cwd?: string | null,
	exe?: string | null,
	root?: string | null,
	openFiles?: string[],
};

/**  通过 `/proc/<pid>` 深入采集的进程详情。 */
export type SshProcessDetail_Serialize = {
	pid: number,
	commandLine?: string | null,
	args: string[],
	cwd?: string | null,
	exe?: string | null,
	root?: string | null,
	openFiles: string[],
};

/**  远程进程信息。 */
export type SshProcessInfo = SshProcessInfo_Serialize | SshProcessInfo_Deserialize;

/**  远程进程信息。 */
export type SshProcessInfo_Deserialize = {
	user: string,
	pid: number,
	cpu: number | null,
	mem: number | null,
	vsz: number | null,
	rss: number | null,
	stat: string,
	start: string,
	time: string,
	command: string,
	ports?: SshProcessPort_Deserialize[],
};

/**  远程进程信息。 */
export type SshProcessInfo_Serialize = {
	user: string,
	pid: number,
	cpu: number | null,
	mem: number | null,
	vsz: number | null,
	rss: number | null,
	stat: string,
	start: string,
	time: string,
	command: string,
	ports: SshProcessPort_Serialize[],
};

/**  进程关联的监听端口。 */
export type SshProcessPort = SshProcessPort_Serialize | SshProcessPort_Deserialize;

/**  进程关联的监听端口。 */
export type SshProcessPort_Deserialize = {
	protocol: string,
	localAddress: string,
	localPort: number,
	state: string,
	remoteAddress?: string | null,
	remotePort?: number | null,
};

/**  进程关联的监听端口。 */
export type SshProcessPort_Serialize = {
	protocol: string,
	localAddress: string,
	localPort: number,
	state: string,
	remoteAddress?: string | null,
	remotePort?: number | null,
};

/**  隧道信息。 */
export type SshTunnelInfo = {
	id: string,
	connectionId: string,
	tunnelType: TunnelType,
	localPort: number,
	remoteHost: string,
	remotePort: number,
	status: string,
	startedAt: number | null,
};

export type StepStatus = "ready" | "pending" | "running" | "passed" | "failed" | "skipped";

export type StepType = "shell" | "sql" | "docker" | "workflow";

/**  Persisted workspace task/action. */
export type Task = {
	id: string,
	task_type: TaskType,
	title: string,
	description: string,
	resource_id: string,
	resource_name: string,
	env_tag: string,
	command: string,
	risk: TaskRisk,
	status: TaskStatus,
	source: TaskSource,
	output: string,
	created_at: number | null,
	updated_at: number | null,
	started_at: number | null,
	finished_at: number | null,
};

export type TaskRisk = "low" | "medium" | "high" | "critical";

export type TaskSource = "user" | "ai" | "system";

export type TaskStatus = "draft" | "blocked" | "confirmed" | "running" | "completed" | "failed" | "cancelled";

export type TaskType = "terminal" | "sql" | "docker" | "server" | "ssh" | "ai" | "workflow";

/**  隧道类型。 */
export type TunnelType = "local" | "remote" | "dynamic";

export type UpdateInfo = {
	available: boolean,
	version: string,
	body: string,
	current_version: string,
};

export type UpsertMcpServiceInput = {
	id: string | null,
	name: string,
	enabled: boolean,
	transportKind: McpTransportKind,
	command: string | null,
	args?: string[],
	env?: McpEnvEntry[],
	cwd: string | null,
	url: string | null,
};

export type Workflow = {
	id: string,
	name: string,
	description: string,
	workflow_type: WorkflowType,
	risk_level: RiskLevel,
	target: string,
	env_tag: string,
	created_at: number | null,
	updated_at: number | null,
};

export type WorkflowDetail = {
	workflow: Workflow,
	steps: WorkflowStep[],
};

export type WorkflowExecution = {
	id: string,
	workflow_id: string,
	status: ExecutionStatus,
	triggered_by: string,
	started_at: number | null,
	finished_at: number | null,
	duration_ms: number | null,
	output: string,
};

export type WorkflowExecutionDetail = {
	execution: WorkflowExecution,
	steps: WorkflowExecutionStep[],
};

export type WorkflowExecutionStep = {
	id: string,
	execution_id: string,
	step_id: string,
	step_order: number,
	name: string,
	step_type: StepType,
	command: string,
	status: StepStatus,
	output: string,
	error: string,
	started_at: number | null,
	finished_at: number | null,
};

export type WorkflowStep = {
	id: string,
	workflow_id: string,
	name: string,
	description: string,
	step_type: StepType,
	command: string,
	step_order: number,
	status: StepStatus,
};

export type WorkflowType = "script" | "template" | "deploy" | "patrol" | "data_flow";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

