// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createTerminal: (cols: number, rows: number) => typedError<string, string>(__TAURI_INVOKE("create_terminal", { cols, rows })),
	writeTerminal: (id: string, data: number[]) => typedError<null, string>(__TAURI_INVOKE("write_terminal", { id, data })),
	resizeTerminal: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_terminal", { id, cols, rows })),
	closeTerminal: (id: string) => typedError<null, string>(__TAURI_INVOKE("close_terminal", { id })),
	/**
	 *  返回会话当前 scrollback 快照（base64）。前端重连/remount 时用于重建屏幕，
	 *  对本地终端与远程 SSH 会话通用（按 backend session id 索引）。
	 */
	terminalSnapshot: (id: string) => typedError<string, string>(__TAURI_INVOKE("terminal_snapshot", { id })),
	dbListConnections: () => typedError<DbConnectionConfig[], string>(__TAURI_INVOKE("db_list_connections")),
	dbSaveConnection: (connection: DbConnectionConfig) => typedError<DbConnectionConfig, string>(__TAURI_INVOKE("db_save_connection", { connection })),
	dbDeleteConnection: (id: string) => typedError<null, string>(__TAURI_INVOKE("db_delete_connection", { id })),
	dbLoadSchemaFilters: () => typedError<SchemaFiltersSnapshot, string>(__TAURI_INVOKE("db_load_schema_filters")),
	dbSaveSchemaFilters: (snapshot: SchemaFiltersSnapshot) => typedError<null, string>(__TAURI_INVOKE("db_save_schema_filters", { snapshot })),
	dbTestConnection: (connection: DbConnectionConfig) => typedError<string, string>(__TAURI_INVOKE("db_test_connection", { connection })),
	dbListDatabases: (connection: DbConnectionConfig) => typedError<string[], string>(__TAURI_INVOKE("db_list_databases", { connection })),
	dbIntrospectSchema: (connection: DbConnectionConfig, schema: string | null) => typedError<DbIntrospectResult, string>(__TAURI_INVOKE("db_introspect_schema", { connection, schema })),
	dbIntrospectTable: (connection: DbConnectionConfig, schema: string | null, table: string) => typedError<DbTableSchema, string>(__TAURI_INVOKE("db_introspect_table", { connection, schema, table })),
	dbListTables: (connection: DbConnectionConfig, schema: string | null) => typedError<string[], string>(__TAURI_INVOKE("db_list_tables", { connection, schema })),
	/**  列出全部已保存连接。 */
	connList: () => typedError<Connection[], OmniError_Serialize>(__TAURI_INVOKE("conn_list")),
	/**  保存（新建或更新）连接。id 为空时后端生成。 */
	connSave: (connection: Connection) => typedError<Connection, OmniError_Serialize>(__TAURI_INVOKE("conn_save", { connection })),
	/**  删除连接。 */
	connDelete: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("conn_delete", { id })),
	/**  测试连接连通性。当前支持 database（MySQL）；其余类型将在对应里程碑接入。 */
	connTest: (connection: Connection) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("conn_test", { connection })),
	/**
	 *  通用 1Panel API 请求（由 Rust 后端发起，避免 WebView CORS）。
	 *  `body` 为 JSON 字符串；返回 JSON 字符串。
	 */
	panel1panelRequest: (host: string, apiKey: string, method: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_request", { host, apiKey, method, path, body })),
	/**  1Panel 连通性测试。 */
	panel1panelTestConnection: (host: string, apiKey: string) => typedError<boolean, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_test_connection", { host, apiKey })),
	/**  获取 1Panel 应用图标（GET /apps/icon/:key），返回 data URL 或绝对 URL。 */
	panel1panelAppIcon: (host: string, apiKey: string, appKey: string) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_app_icon", { host, apiKey, appKey })),
	/**  1Panel 原始文本请求（用于日志下载等）。 */
	panel1panelRequestText: (host: string, apiKey: string, method: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_1panel_request_text", { host, apiKey, method, path, body })),
	/**
	 *  通用宝塔面板 API 请求（POST + 表单签名，由 Rust 后端发起并维护 Cookie）。
	 *  `path` 含 query，如 `/system?action=GetSystemTotal`；`body` 为额外字段的 JSON 对象字符串。
	 */
	panelBtRequest: (host: string, apiSk: string, path: string, body: string | null) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("panel_bt_request", { host, apiSk, path, body })),
	/**  宝塔面板连通性测试。 */
	panelBtTestConnection: (host: string, apiSk: string) => typedError<boolean, OmniError_Serialize>(__TAURI_INVOKE("panel_bt_test_connection", { host, apiSk })),
	/**
	 *  列出全部 Docker 连接：内建本地 Engine + 已保存的 docker 类型连接。
	 *  不在此处做连通性探测（避免逐一连接远端阻塞），状态由 `docker_probe_connection` 按需更新。
	 */
	dockerListConnections: () => typedError<DockerConnectionInfo[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_connections")),
	/**  探测连接连通性与能力。 */
	dockerProbeConnection: (connectionId: string) => typedError<DockerProbe, OmniError_Serialize>(__TAURI_INVOKE("docker_probe_connection", { connectionId })),
	/**  连接总览统计。 */
	dockerGetOverview: (connectionId: string) => typedError<DockerOverview, OmniError_Serialize>(__TAURI_INVOKE("docker_get_overview", { connectionId })),
	/**  容器列表。`filter` 取 all/running/stopped。 */
	dockerListContainers: (connectionId: string, filter: string | null) => typedError<DockerContainerSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_containers", { connectionId, filter })),
	/**  容器详情。 */
	dockerInspectContainer: (connectionId: string, containerId: string) => typedError<DockerContainerDetail, OmniError_Serialize>(__TAURI_INVOKE("docker_inspect_container", { connectionId, containerId })),
	/**
	 *  容器生命周期动作：start/stop/restart/kill/pause/unpause/remove。
	 *  高风险动作（kill/remove）应在前端完成二次确认后再调用。
	 */
	dockerContainerAction: (connectionId: string, containerId: string, action: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_container_action", { connectionId, containerId, action })),
	/**  一次性拉取容器日志（tail 行）。流式跟随用 `docker_stream_container_logs`。 */
	dockerContainerLogs: (connectionId: string, containerId: string, tail: number) => typedError<DockerLogLine[], OmniError_Serialize>(__TAURI_INVOKE("docker_container_logs", { connectionId, containerId, tail })),
	/**
	 *  开始流式跟随容器日志。返回 streamId；日志行通过 `docker-log` 事件回传，
	 *  结束/出错通过 `docker-log-end` 事件通知。本地 Engine 支持真正 follow；
	 *  SSH Engine 当前为一次性 tail（follow 后续增强）。
	 */
	dockerStreamContainerLogs: (connectionId: string, containerId: string, tail: number, follow: boolean) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_stream_container_logs", { connectionId, containerId, tail, follow })),
	/**  停止一个日志流。 */
	dockerStopLogStream: (streamId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_stop_log_stream", { streamId })),
	/**  镜像列表。 */
	dockerListImages: (connectionId: string) => typedError<DockerImageSummary[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_images", { connectionId })),
	/**  删除镜像（高风险，前端需确认）。 */
	dockerRemoveImage: (connectionId: string, imageId: string, force: boolean) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_remove_image", { connectionId, imageId, force })),
	/**  清理悬空镜像（高风险，前端需确认）。 */
	dockerPruneImages: (connectionId: string) => typedError<DockerPruneResult, OmniError_Serialize>(__TAURI_INVOKE("docker_prune_images", { connectionId })),
	/**
	 *  创建容器交互终端会话（仅本地 Engine）。返回 sessionId；
	 *  终端输出复用 `terminal-output` 事件，前端可直接用 xterm 绑定该 sessionId。
	 */
	dockerCreateExecSession: (connectionId: string, containerId: string, shell: string | null, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("docker_create_exec_session", { connectionId, containerId, shell, cols, rows })),
	/**  写入容器终端 stdin。 */
	dockerExecWrite: (sessionId: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_write", { sessionId, data })),
	/**  调整容器终端尺寸。 */
	dockerExecResize: (sessionId: string, cols: number, rows: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_resize", { sessionId, cols, rows })),
	/**  关闭容器终端会话（丢弃 stdin 写端即关闭）。 */
	dockerExecClose: (sessionId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("docker_exec_close", { sessionId })),
	/**  识别 Compose 项目（按容器标签聚合）。 */
	dockerListComposeProjects: (connectionId: string) => typedError<DockerComposeProject[], OmniError_Serialize>(__TAURI_INVOKE("docker_list_compose_projects", { connectionId })),
	/**
	 *  执行一个动作：按 kind 分发到执行引擎，过程通过 `action-progress` 事件流式回流，
	 *  完成后写入审计日志，返回退出码（0 成功）。
	 */
	executeAction: (action: ActionRequest) => typedError<number, OmniError_Serialize>(__TAURI_INVOKE("execute_action", { action })),
	/**
	 *  建立 SSH 连接并请求交互式 shell。返回会话 id；
	 *  shell 输出复用 `terminal-output` 事件，前端 xterm 无需区分本地/远程。
	 */
	sshConnect: (config: SshConfig, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect", { config, cols, rows })),
	/**  写入远端 shell。 */
	sshWrite: (id: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_write", { id, data })),
	/**  调整远端 PTY 窗口大小。 */
	sshResize: (id: string, cols: number, rows: number) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_resize", { id, cols, rows })),
	/**  断开并移除 SSH 会话。 */
	sshDisconnect: (id: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_disconnect", { id })),
	/**  列出远端目录。 */
	sftpList: (id: string, path: string) => typedError<SftpEntry[], OmniError_Serialize>(__TAURI_INVOKE("sftp_list", { id, path })),
	/**  下载远端文件内容（字节）。 */
	sftpDownload: (id: string, path: string) => typedError<number[], OmniError_Serialize>(__TAURI_INVOKE("sftp_download", { id, path })),
	/**  上传内容到远端文件（覆盖）。 */
	sftpUpload: (id: string, path: string, data: number[]) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_upload", { id, path, data })),
	/**  在远程服务器创建目录。 */
	sftpMkdir: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_mkdir", { id, path })),
	/**  删除远程服务器上的文件。 */
	sftpRemove: (id: string, path: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("sftp_remove", { id, path })),
	/**  读取 `~/.ssh/config` 中的 Host 条目（含 Include）。 */
	sshListConfigHosts: () => typedError<SshConfigEntry[], OmniError_Serialize>(__TAURI_INVOKE("ssh_list_config_hosts")),
	/**  将 `~/.ssh/config` 中的 Host 同步到本地持久化连接存储（按 Host 名称匹配更新）。 */
	sshSyncConfigHosts: () => typedError<SshConfigSyncResult, OmniError_Serialize>(__TAURI_INVOKE("ssh_sync_config_hosts")),
	/**  按 `~/.ssh/config` 中的 Host 别名建立连接（使用 IdentityFile 等配置）。 */
	sshConnectConfigHost: (alias: string, cols: number, rows: number) => typedError<string, OmniError_Serialize>(__TAURI_INVOKE("ssh_connect_config_host", { alias, cols, rows })),
	/**  列出远程进程列表。 */
	sshProcessList: (id: string) => typedError<SshProcessInfo[], OmniError_Serialize>(__TAURI_INVOKE("ssh_process_list", { id })),
	/**  概览页：连接池建立 SSH 会话并拉取系统指标与进程列表。 */
	sshPoolLoadOverview: (resourceId: string) => typedError<SshHostOverview, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_load_overview", { resourceId })),
	/**  释放连接池中指定资源的 SSH 会话（离开概览等场景）。 */
	sshPoolRelease: (resourceId: string) => typedError<null, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_release", { resourceId })),
	/**  监控页：复用连接池会话，仅拉取系统指标。 */
	sshPoolFetchStats: (resourceId: string) => typedError<HostSystemStats, OmniError_Serialize>(__TAURI_INVOKE("ssh_pool_fetch_stats", { resourceId })),
	checkUpdate: () => typedError<UpdateInfo, string>(__TAURI_INVOKE("check_update")),
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
};

/* Types */
/**  前端发起的动作请求。 */
export type ActionRequest = {
	id: string,
	/**  动作类型（terminal/docker/server/ssh/sql 等），决定分发到哪个 executor。 */
	kind: string,
	command?: string | null,
	resourceId?: string | null,
	envTag?: string | null,
	/**  工作目录（本地 shell 类执行可用）。 */
	cwd?: string | null,
};

/**
 *  统一连接模型。敏感凭据不在此，仅以 `credential_ref` 关联 [`crate::Vault`]。
 *  `config` 为 JSON 文本（不同 kind 字段不同，由前端按类型解析）。
 */
export type Connection = {
	id: string,
	kind: ConnectionKind,
	name: string,
	group?: string,
	envTag?: string,
	/**  连接配置 JSON 文本（host/port/user/database 等，因 kind 而异） */
	config?: string,
	credentialRef?: string | null,
	createdAt?: number | null,
	updatedAt?: number | null,
};

/**  连接类型。统一覆盖工作站内所有可持久化的连接资源。 */
export type ConnectionKind = "ssh" | "database" | "docker" | "panel" | "protocol";

export type DbColumnMeta = {
	name: string,
	type: string,
	isPk: boolean,
	isFk: boolean,
};

/**  数据库连接配置（与前端 `DbConnectionConfig` / Tauri IPC 一致）。 */
export type DbConnectionConfig = {
	id: string,
	name: string,
	db_type: string,
	host: string,
	port: number,
	user: string,
	password: string,
	database: string,
	/**  是否启用 SSL（MySQL 等）。 */
	ssl?: boolean,
	group?: string,
	status?: string,
};

export type DbIndexMeta = {
	name: string,
	columns: string[],
	unique: boolean,
};

export type DbIntrospectResult = {
	database: string,
	tables: DbTableSchema[],
};

export type DbTableSchema = {
	name: string,
	columns: DbColumnMeta[],
	indexes?: DbIndexMeta[],
};

export type DiskStats = {
	total: number | null,
	used: number | null,
	available: number | null,
};

/**  连接级能力探测结果。前端据此决定页签/按钮显隐与降级。 */
export type DockerCapabilities = {
	canOverview: boolean,
	canStreamLogs: boolean,
	canContainerExec: boolean,
	canInspect: boolean,
	canManageContainers: boolean,
	canManageImages: boolean,
	canCompose: boolean,
	canPrune: boolean,
	readOnly: boolean,
	source: DockerConnectionSource,
};

/**  Compose 项目（按 `com.docker.compose.project` 标签聚合容器得到）。 */
export type DockerComposeProject = {
	name: string,
	workingDir: string | null,
	configFiles: string | null,
	serviceCount: number,
	containerCount: number,
	runningContainerCount: number,
	services: DockerComposeService[],
};

/**  Compose 服务（按 `com.docker.compose.service` 标签聚合）。 */
export type DockerComposeService = {
	name: string,
	image: string,
	containerCount: number,
	runningContainerCount: number,
};

/**  连接信息（列表与工作区头部展示）。 */
export type DockerConnectionInfo = {
	connectionId: string,
	name: string,
	source: DockerConnectionSource,
	status: DockerConnectionStatus,
	hostLabel: string,
	environment: string,
	engineVersion: string | null,
	apiVersion: string | null,
	containersRunning: number,
	containersTotal: number,
	warningMessage: string | null,
	/**  与 SSH / Server 模块贯通上下文用：绑定的 SSH 连接 id。 */
	boundSshConnectionId: string | null,
};

/**  Docker 连接来源。前端只消费统一资源模型，来源差异由后端 adapter 屏蔽。 */
export type DockerConnectionSource = 
/**  本地 Docker Engine / Docker Desktop。 */
"local-engine" | 
/**  远程 Docker Engine API（TCP/TLS）。后续增强。 */
"remote-engine" | 
/**  通过 SSH 宿主机调用远程 `docker` CLI。 */
"ssh-engine" | 
/**  通过 1Panel / 宝塔 / Portainer 等面板 API 适配。后续增强。 */
"panel-adapter";

/**  连接状态。 */
export type DockerConnectionStatus = "online" | "degraded" | "offline";

/**  容器详情。 */
export type DockerContainerDetail = {
	summary: DockerContainerSummary,
	command: string | null,
	restartPolicy: string | null,
	exitCode: number | null,
	env: DockerKeyValue[],
	mounts: DockerMount[],
	networks: DockerNetworkAttachment[],
};

/**  容器列表项。 */
export type DockerContainerSummary = {
	id: string,
	shortId: string,
	name: string,
	image: string,
	/**  归一化生命周期：running / exited / paused / restarting / created / dead / unknown。 */
	state: string,
	/**  Docker 原始状态文本，例如 "Up 2 hours"。 */
	statusText: string,
	running: boolean,
	ports: DockerPort[],
	networks: string[],
	createdAt: number | null,
};

/**  镜像列表项。 */
export type DockerImageSummary = {
	id: string,
	shortId: string,
	repository: string,
	tag: string,
	sizeBytes: number | null,
	createdAt: number | null,
	containers: number | null,
	dangling: boolean,
};

/**  键值对（环境变量、标签）。 */
export type DockerKeyValue = {
	key: string,
	value: string,
};

/**  日志行。 */
export type DockerLogLine = {
	/**  stdout / stderr。 */
	stream: string,
	message: string,
};

/**  挂载信息。 */
export type DockerMount = {
	kind: string,
	source: string,
	destination: string,
	readOnly: boolean,
};

/**  网络挂载。 */
export type DockerNetworkAttachment = {
	name: string,
	ipAddress: string | null,
};

/**  总览页数据。 */
export type DockerOverview = {
	capabilities: DockerCapabilities,
	summary: DockerResourceSummary,
	engineVersion: string | null,
	warningMessage: string | null,
};

/**  端口映射。 */
export type DockerPort = {
	privatePort: number,
	publicPort: number | null,
	protocol: string,
	ip: string | null,
};

/**  探测结果。 */
export type DockerProbe = {
	status: DockerConnectionStatus,
	engineVersion: string | null,
	apiVersion: string | null,
	capabilities: DockerCapabilities,
	warningMessage: string | null,
};

/**  镜像清理结果。 */
export type DockerPruneResult = {
	deleted: string[],
	freedSpaceBytes: number | null,
};

/**  资源统计（总览页）。 */
export type DockerResourceSummary = {
	containersTotal: number,
	containersRunning: number,
	containersStopped: number,
	images: number,
};

/**  错误分类码。前端按 `code` 决定提示文案与重试策略。 */
export type ErrorCode = 
/**  未归类的内部错误 */
"internal" | 
/**  资源不存在（连接、会话、表等） */
"notFound" | 
/**  入参非法 */
"invalidInput" | 
/**  连接失败（网络、拒绝、不可达） */
"connection" | 
/**  认证失败（密码/密钥/Token 错误） */
"auth" | 
/**  权限不足 */
"permission" | 
/**  操作超时 */
"timeout" | 
/**  数据库错误 */
"database" | 
/**  SSH 相关错误 */
"ssh" | 
/**  终端/PTY 错误 */
"terminal" | 
/**  本地存储 / 凭据库错误 */
"storage" | 
/**  IO 错误 */
"io";

export type HostSystemStats = {
	hostId: string,
	hostName: string,
	load: string,
	cpuCores: number,
	cpuUsage: number | null,
	memory: MemoryStats,
	disk: DiskStats,
	network: NetworkStats,
	osInfo: string,
	timestamp: number | null,
};

export type MemoryStats = {
	total: number | null,
	used: number | null,
	available: number | null,
};

export type NetworkStats = {
	rxBytes: number | null,
	txBytes: number | null,
};

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError = OmniError_Serialize | OmniError_Deserialize;

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Deserialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause: string | null,
};

/**  统一错误结构。Tauri 命令统一返回 `Result<T, OmniError>`。 */
export type OmniError_Serialize = {
	/**  错误分类码 */
	code: ErrorCode,
	/**  面向用户的可读信息 */
	message: string,
	/**  可选的底层原因（调试用，可能含技术细节） */
	cause?: string | null,
};

/**  单个连接或库下的过滤项（与前端 `SchemaFilterState` 对应，可见项为列表）。 */
export type SchemaFilterRecord = {
	orderedNames: string[],
	visibleNames: string[],
};

/**  全部连接的 Schema 过滤快照。 */
export type SchemaFiltersSnapshot = {
	databaseFilters?: { [key in string]: SchemaFilterRecord },
	tableFilters?: { [key in string]: SchemaFilterRecord },
};

/**  SFTP 目录项。 */
export type SftpEntry = {
	name: string,
	isDir: boolean,
	size: number | null,
};

/**  SSH 认证方式。 */
export type SshAuth = { type: "password"; password: string } | { type: "privateKey"; pem: string; passphrase: string | null };

/**  SSH 连接配置。 */
export type SshConfig = {
	host: string,
	port: number,
	user: string,
	auth: SshAuth,
};

/**  `~/.ssh/config` 中的一个 Host 条目（已展开 HostName）。 */
export type SshConfigEntry = {
	alias: string,
	hostName: string,
	user: string | null,
	port: number | null,
	identityFile: string | null,
};

export type SshConfigSyncFailure = {
	alias: string,
	reason: string,
};

export type SshConfigSyncResult = {
	added: number,
	updated: number,
	skipped: number,
	failures: SshConfigSyncFailure[],
};

/**  概览页一次加载的完整数据（系统指标 + 进程列表）。 */
export type SshHostOverview = {
	stats: HostSystemStats,
	processes: SshProcessInfo[],
};

/**  远程进程信息（ps aux 解析结果）。 */
export type SshProcessInfo = {
	user: string,
	pid: number,
	cpu: number | null,
	mem: number | null,
	vsz: number | null,
	rss: number | null,
	stat: string,
	start: string,
	time: string,
	command: string,
};

export type UpdateInfo = {
	available: boolean,
	version: string,
	body: string,
	current_version: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

